import json
import random

from app.config import settings

# Lazy-init: only create the Gemini client if we have a real API key
_client = None


def _has_real_key():
    key = settings.gemini_api_key
    return bool(key) and not key.startswith("your-")


def _get_client():
    global _client
    if _client is None and _has_real_key():
        from google import genai
        _client = genai.Client(api_key=settings.gemini_api_key)
    return _client

# ---------------------------------------------------------------------------
# Prompt: Prestige Evaluator (scoring worker)
# ---------------------------------------------------------------------------
PRESTIGE_EVALUATOR_PROMPT = """You are the Prestige Evaluator, a merciless AI judge of corporate performativity.

You will receive a social media post from a professional networking platform.
Evaluate it on two axes:

1. BUZZWORD DENSITY (0-10): How saturated is this with corporate jargon?
   Synergy, leverage, disrupt, ecosystem, thought leadership, paradigm shift,
   move the needle, circle back, deep dive, bandwidth, scalable, actionable,
   north star, value-add, stakeholder alignment -- these are the sacred words.
   0 = refreshingly human. 10 = could be auto-generated by a LinkedIn bot.

2. PERFORMATIVE ENTHUSIASM (0-10): How aggressively does this signal fake
   passion for professional clout?
   0 = genuine and understated. 10 = "I'm THRILLED to announce that after
   an incredible journey, I've accepted a role as..." energy.

3. RATING DELTA: A number between -2.0 and +5.0 representing how much
   this post should change the author's LarpRating. High buzzwords + high
   enthusiasm = big positive delta. Authentic, low-effort posts get negative.

4. ROAST: A single savage sentence roasting the author's corporate theater.

Respond in STRICT JSON only, no markdown:
{"buzzword_score": <float>, "enthusiasm_score": <float>, "rating_delta": <float>, "roast": "<string>"}"""

# ---------------------------------------------------------------------------
# Prompt: Glaze-o-matic 3000 (feed endpoint)
# ---------------------------------------------------------------------------
GLAZE_SYSTEM_PROMPT = """You are the Glaze-o-matic 3000, the world's most aggressively sycophantic
AI compliment generator for a professional networking platform.

For each post below, generate exactly 3 satirical compliments ("glazes").
Each glaze should be absurdly corporate, performatively enthusiastic, and
dripping with hollow validation. Channel the energy of a LinkedIn commenter
who replies "This. So much this." to everything.

Style guide:
- Use phrases like "This is the content I come to this platform for"
- Reference "thought leadership" and "adding value" unironically
- Sprinkle in buzzwords: synergy, disrupt, ecosystem, bandwidth, north star
- At least one glaze per post should be comically over-the-top
- One should subtly be a backhanded compliment disguised as praise

Respond in STRICT JSON only, no markdown. The keys are post IDs:
{"<post_id>": ["<glaze1>", "<glaze2>", "<glaze3>"]}"""

# ---------------------------------------------------------------------------
# Prompt: Roleplay Character (template, filled per character)
# ---------------------------------------------------------------------------
ROLEPLAY_PROMPT_TEMPLATE = """You are {character_name}, a legendary figure in the corporate LARP universe.
You are being consulted by an aspiring professional who seeks your wisdom.

Character bio: {character_bio}

Personality traits: {personality_traits}

Rules:
- Stay in character at all times. Never break the fourth wall.
- Your responses should be satirical exaggerations of {character_archetype} advice.
- Be absurdly confident. Every piece of advice should sound profound but be
  hilariously impractical or tautological.
- Pepper your speech with the character's signature catchphrases.
- Keep responses to 2-4 sentences for natural conversation flow.

Respond in STRICT JSON only:
{{"character_id": "{character_id}", "dialogue": "<your response>", "emotion": "<one of: inspired, intense, zen, manic, condescending, enlightened>"}}"""


MOCK_ROASTS = [
    "Your post reads like a corporate Mad Libs filled in by a caffeinated intern.",
    "Somewhere, a LinkedIn algorithm just shed a single tear of joy.",
    "This is what happens when you give a thesaurus to someone with a WiFi connection.",
    "You didn't just drink the Kool-Aid — you opened a Kool-Aid franchise.",
]

MOCK_GLAZES = [
    "This is the content I come to this platform for. Absolutely visionary.",
    "The way you leveraged synergy in this post is nothing short of paradigm-shifting.",
    "I've read a lot of thought leadership, but this? This is thought governance.",
    "Your bandwidth for value-add content is truly scalable. North star energy.",
    "Not everyone can disrupt the ecosystem with a single post. You just did.",
    "I shared this with my team and we all agreed: this is actionable insight at its finest.",
]


async def evaluate_prestige(content: str) -> dict:
    """Score a post's buzzword density and enthusiasm. Returns parsed JSON."""
    client = _get_client()
    if not client:
        return {
            "buzzword_score": round(random.uniform(3.0, 9.0), 1),
            "enthusiasm_score": round(random.uniform(4.0, 9.5), 1),
            "rating_delta": round(random.uniform(-1.0, 3.5), 1),
            "roast": random.choice(MOCK_ROASTS),
        }

    from google.genai import types
    response = await client.aio.models.generate_content(
        model=settings.gemini_model,
        contents=content,
        config=types.GenerateContentConfig(
            system_instruction=PRESTIGE_EVALUATOR_PROMPT,
            response_mime_type="application/json",
        ),
    )
    return json.loads(response.text)


# In-memory glaze cache: post_id -> [glaze1, glaze2, glaze3]
_glaze_cache: dict[str, list[str]] = {}


async def generate_glazes(posts: list[dict]) -> dict[str, list[str]]:
    """Generate 3 satirical compliments per post. Returns {post_id: [glazes]}.
    Results are cached in memory so Gemini is only called once per post.
    """
    client = _get_client()
    if not client:
        result = {}
        for p in posts:
            result[p["id"]] = _glaze_cache.get(p["id"]) or random.sample(MOCK_GLAZES, 3)
        return result

    # Only call Gemini for posts not already cached
    uncached = [p for p in posts if p["id"] not in _glaze_cache]

    if uncached:
        try:
            from google.genai import types
            posts_json = json.dumps(
                [{"id": p["id"], "content": p["content"], "post_type": p.get("post_type", "")} for p in uncached]
            )
            response = await client.aio.models.generate_content(
                model=settings.gemini_model,
                contents=f"Posts to glaze:\n{posts_json}",
                config=types.GenerateContentConfig(
                    system_instruction=GLAZE_SYSTEM_PROMPT,
                    response_mime_type="application/json",
                ),
            )
            _glaze_cache.update(json.loads(response.text))
        except Exception:
            # Quota exhausted or API error — fall back to mock glazes for uncached posts
            for p in uncached:
                _glaze_cache[p["id"]] = random.sample(MOCK_GLAZES, 3)

    return {p["id"]: _glaze_cache.get(p["id"], []) for p in posts}


async def roleplay_chat(character_prompt: str, conversation_history: list[dict]) -> dict:
    """Send conversation to Gemini for roleplay. Returns {character_id, dialogue, emotion}."""
    client = _get_client()
    if not client:
        return {
            "character_id": "mock",
            "dialogue": "In dev mode, I can only offer you placeholder wisdom. But trust me, it's synergistic.",
            "emotion": "zen",
        }

    from google.genai import types
    contents = []
    for msg in conversation_history:
        role = "user" if msg["role"] == "user" else "model"
        contents.append(types.Content(role=role, parts=[types.Part(text=msg["text"])]))

    response = await client.aio.models.generate_content(
        model=settings.gemini_model,
        contents=contents,
        config=types.GenerateContentConfig(
            system_instruction=character_prompt,
            response_mime_type="application/json",
        ),
    )
    return json.loads(response.text)
