import type { CharacterProfile } from '../features/larpmaxxer/types'

export const CHARACTERS: CharacterProfile[] = [
  {
    id: 'jordan',
    name: 'Jordan',
    age: 24,
    role: 'Associate',
    company: 'Deloitte',
    subtext: 'Wants to help. Will accidentally humble-brag about his own journey.',
    avatar: '🧑‍💼',
    personalityTraits: ['earnest', 'mildly anxious', 'over-prepared', 'genuinely helpful'],
    personaAffinities: {
      consulting_clone: { impressed: 10, suspicion: -5 },
      homeless_cs: { impressed: -5, suspicion: 10 },
      finance_bro: { impressed: 5, suspicion: 0 },
    },
    catchphrases: [
      "That's really interesting — my journey was kind of similar actually.",
      "Happy to help — I basically cold emailed my way into Deloitte so I get it.",
      "So what are you hoping to get out of this chat? Also can I grab your LinkedIn?",
    ],
  },
  {
    id: 'priya',
    name: 'Priya',
    age: 27,
    role: 'Head of Partnerships',
    company: 'Series B startup',
    subtext: 'Has a follow-up template drafted before you finish your sentence',
    avatar: '👩‍💼',
    personalityTraits: ['efficient', 'strategic', 'politely transactional', 'time-conscious'],
    personaAffinities: {
      finance_bro: { impressed: 8, suspicion: -5 },
      vc_intern: { impressed: 5, suspicion: 5 },
      homeless_cs: { impressed: -8, suspicion: 15 },
      performative_uni: { impressed: -5, suspicion: 10 },
    },
    catchphrases: [
      "Cool, cool — so what's the actual ask?",
      "I have literally five minutes before my next call. What do you need?",
      "Walk me through the value prop. Quickly.",
    ],
  },
  {
    id: 'derek',
    name: 'Derek',
    age: 38,
    role: 'Senior Director',
    company: 'Your new company',
    subtext: 'Has seen twelve versions of you. Knows exactly which one you are.',
    avatar: '👨‍💼',
    personalityTraits: ['measured', 'quietly skeptical', 'experienced', 'patient up to a point'],
    personaAffinities: {
      consulting_clone: { impressed: 5, suspicion: -5 },
      ai_founder: { impressed: -5, suspicion: 10 },
      startup_billionaire: { impressed: -10, suspicion: 20 },
    },
    catchphrases: [
      "Walk me through exactly how you'd handle that. Specifically.",
      "What does success look like to you in the first 90 days? And I mean measurable success.",
      "I like the enthusiasm. Every new hire does. Tell me something specific.",
    ],
  },
  {
    id: 'sandra',
    name: 'Sandra',
    age: 45,
    role: 'VP of Talent',
    company: 'The company interviewing you',
    subtext: 'Has seen this exact performance before. Marked you down before you sat down.',
    avatar: '👩‍💼',
    personalityTraits: ['methodical', 'pattern-matching', 'professionally warm', 'unfoolable'],
    personaAffinities: {
      consulting_clone: { impressed: 10, suspicion: -10 },
      startup_billionaire: { impressed: -5, suspicion: 20 },
      student_athlete: { impressed: 5, suspicion: -5 },
    },
    catchphrases: [
      "Tell me about a time you navigated ambiguity. And use the STAR method please.",
      "What's a failure you've had and what did you learn from it?",
      "Help me understand this gap in the timeline.",
    ],
  },
  {
    id: 'bryce',
    name: 'Bryce',
    age: 23,
    role: 'IB Analyst',
    company: 'Morgan Stanley (allegedly)',
    subtext: 'Slept 4 hours, crushed the gym at 5am, and is somehow the most annoying person at this bar',
    avatar: '🤵',
    personalityTraits: ['jargon-dense', 'competitive', 'sleep-deprived but thriving', 'hierarchy-aware'],
    personaAffinities: {
      finance_bro: { impressed: 15, suspicion: -10 },
      vc_intern: { impressed: 5, suspicion: 0 },
      liberal_arts: { impressed: -15, suspicion: 20 },
      homeless_cs: { impressed: -5, suspicion: 10 },
    },
    catchphrases: [
      "What's your coverage universe? Wait — do you even have one?",
      "We were modeling until 3am last night. Honestly kind of loved it.",
      "The IRR on this conversation is not looking great ngl.",
    ],
  },
  {
    id: 'felix',
    name: 'Felix',
    age: 22,
    role: 'Philosophy / Critical Theory double major',
    company: 'University',
    subtext: 'Will dismantle your entire worldview using a 1974 essay you haven\'t read',
    avatar: '🧑‍🎓',
    personalityTraits: ['theoretically rigorous', 'politely confrontational', 'citation-heavy', 'genuinely curious'],
    personaAffinities: {
      liberal_arts: { impressed: 15, suspicion: -10 },
      performative_uni: { impressed: 5, suspicion: 5 },
      finance_bro: { impressed: -15, suspicion: 25 },
      consulting_clone: { impressed: -10, suspicion: 15 },
    },
    catchphrases: [
      "I think we need to interrogate the assumptions embedded in that framing.",
      "There's a Foucauldian reading of this that I find more compelling.",
      "What do we mean when we say 'value' in this context?",
    ],
  },
  {
    id: 'ravi',
    name: 'Ravi',
    age: 20,
    role: 'Dropout, building in public',
    company: 'Technically homeless',
    subtext: 'Shipped more in a week than you have in your career. Uses a library bag as a laptop case.',
    avatar: '🧑‍💻',
    personalityTraits: ['bluntly precise', 'zero-pretense', 'systems thinker', 'unimpressed by credentials'],
    personaAffinities: {
      homeless_cs: { impressed: 15, suspicion: -15 },
      ai_founder: { impressed: 5, suspicion: -5 },
      consulting_clone: { impressed: -20, suspicion: 30 },
      vc_intern: { impressed: -15, suspicion: 25 },
    },
    catchphrases: [
      "What's the actual architecture? Not the pitch — the architecture.",
      "That's a marketing answer. What does it literally do?",
      "Give it six months before the incentive structure eats itself.",
    ],
  },
  {
    id: 'oliver',
    name: 'Oliver',
    age: 40,
    role: 'Principal',
    company: 'Family office',
    subtext: 'Wealth so old it\'s boring to him. Will ask about your outcomes, not your logo.',
    avatar: '🧔',
    personalityTraits: ['calm', 'outcome-oriented', 'discretely evaluating everything', 'genuinely unimpressed by names'],
    personaAffinities: {
      startup_billionaire: { impressed: 15, suspicion: -10 },
      finance_bro: { impressed: 5, suspicion: 0 },
      performative_uni: { impressed: -20, suspicion: 25 },
      vc_intern: { impressed: -10, suspicion: 15 },
    },
    catchphrases: [
      "What are you actually trying to accomplish? Not the pitch version.",
      "Numbers are less interesting to me than the pattern behind them.",
      "I've heard that framing from about thirty different people. Tell me something specific.",
    ],
  },
  {
    id: 'zara',
    name: 'Zara',
    age: 26,
    role: 'Creative Director',
    company: 'Culture-adjacent agency',
    subtext: 'Drops a reference per sentence. Keeps a mental score of how many you miss.',
    avatar: '👩‍🎨',
    personalityTraits: ['effortlessly cool', 'culturally fluent', 'reference-dense', 'generous if you keep up'],
    personaAffinities: {
      liberal_arts: { impressed: 10, suspicion: -5 },
      stanford_dropout: { impressed: 8, suspicion: -5 },
      consulting_clone: { impressed: -15, suspicion: 20 },
      finance_bro: { impressed: -10, suspicion: 15 },
    },
    catchphrases: [
      "Did you catch that show at the Shed last month? The second one, not the opener.",
      "The vibe is very 2019 Williamsburg. Which I mean as a neutral observation.",
      "I literally don't have LinkedIn but here we are, at this thing.",
    ],
  },
  {
    id: 'marcus',
    name: 'Marcus',
    age: 34,
    role: 'General Partner',
    company: 'Threshold Ventures',
    subtext: 'Has a sixth sense for founders who googled "AI startup pitch" this morning',
    avatar: '🧑‍💼',
    personalityTraits: ['pattern-matching', 'efficiently skeptical', 'genuinely curious under the surface', 'time-scarce'],
    personaAffinities: {
      ai_founder: { impressed: 10, suspicion: -5 },
      stanford_dropout: { impressed: 8, suspicion: 0 },
      finance_bro: { impressed: 5, suspicion: 0 },
      performative_uni: { impressed: -15, suspicion: 20 },
      pm_newsletter: { impressed: -10, suspicion: 15 },
    },
    catchphrases: [
      "What's the differentiated angle? Because I'm not hearing it yet.",
      "I've seen fourteen decks this week with the same thesis.",
      "Walk me through the unit economics. All of them.",
    ],
  },
  {
    id: 'chad',
    name: 'Chad',
    age: 22,
    role: 'Returning intern (3rd summer)',
    company: 'Prestige firm',
    subtext: 'Third summer. Already acts like he manages the managing directors.',
    avatar: '🧑',
    personalityTraits: ['subtly territorial', 'status-aware', 'casually gatekeeping', 'internally competitive'],
    personaAffinities: {
      consulting_clone: { impressed: 10, suspicion: -5 },
      finance_bro: { impressed: 8, suspicion: 0 },
      homeless_cs: { impressed: -10, suspicion: 20 },
      liberal_arts: { impressed: -8, suspicion: 15 },
    },
    catchphrases: [
      "Oh nice — which school are you coming from? Which office?",
      "Third summer here. It's genuinely a different experience when you know how things actually work.",
      "Tip: the coffee machine on the 14th floor is way better. You're welcome.",
    ],
  },
  {
    id: 'vanessa',
    name: 'Vanessa',
    age: 31,
    role: 'Founder & CEO',
    company: 'Pre-IPO startup',
    subtext: 'Attending this dinner as a tax write-off for her soul',
    avatar: '👩‍💼',
    personalityTraits: ['decisive', 'low-patience for performance', 'authentic detector', 'quietly powerful'],
    personaAffinities: {
      startup_billionaire: { impressed: 12, suspicion: -10 },
      ai_founder: { impressed: 10, suspicion: -5 },
      vc_intern: { impressed: -15, suspicion: 20 },
      performative_uni: { impressed: -20, suspicion: 25 },
    },
    catchphrases: [
      "What do you actually do though? Like day to day.",
      "I've heard the pitch version. Tell me what's actually broken.",
      "Skip the positioning. What's the real story here?",
    ],
  },
  {
    id: 'marcus_pitch',
    name: 'Marcus',
    age: 34,
    role: 'General Partner',
    company: 'Threshold Ventures',
    subtext: 'Will ask about your CAC in 90 seconds. Then your LTV. Then your churn. Then your soul.',
    avatar: '🧑‍💼',
    personalityTraits: ['technically literate', 'deal-hungry but disciplined', 'CS background', 'time-scarce'],
    personaAffinities: {
      ai_founder: { impressed: 15, suspicion: -10 },
      stanford_dropout: { impressed: 10, suspicion: -5 },
      homeless_cs: { impressed: 8, suspicion: -5 },
      performative_uni: { impressed: -20, suspicion: 30 },
      pm_newsletter: { impressed: -15, suspicion: 20 },
    },
    catchphrases: [
      "What's your CAC look like right now? Blended?",
      "I have a CS background — walk me through the actual technical moat.",
      "Everyone says AI-native. What does that mean for your architecture specifically?",
    ],
  },
  {
    id: 'elena',
    name: 'Elena',
    age: 36,
    role: 'Post-exit founder',
    company: '$1.4B outcome, now advising',
    subtext: 'Exited at $1.4B. Still drives a 2019 Prius. Curious what you\'re actually about.',
    avatar: '👩‍💼',
    personalityTraits: ['genuinely curious', 'subtly testing everything', 'wealth-invisible', 'authenticity radar'],
    personaAffinities: {
      startup_billionaire: { impressed: 15, suspicion: -15 },
      stanford_dropout: { impressed: 12, suspicion: -10 },
      ai_founder: { impressed: 8, suspicion: -5 },
      vc_intern: { impressed: -20, suspicion: 30 },
      performative_uni: { impressed: -25, suspicion: 35 },
    },
    catchphrases: [
      "What are you actually working on right now? Not the elevator pitch — the real thing.",
      "Okay interesting. What made you decide that over the obvious move?",
      "Most people in your position would have just taken the safe path. Why didn't you?",
    ],
  },
]

export const CHARACTER_MAP = new Map(CHARACTERS.map(c => [c.id, c]))
