import type { Persona } from '../features/larpmaxxer/types'

export const PERSONAS: Persona[] = [
  {
    id: 'finance_bro',
    name: 'Finance Bro',
    icon: '💰',
    description: 'Woke up at 5am, crushed the gym, and is already talking about deal flow. IRR and basis points are his love language.',
    cluster: 'finance',
    behaviorSignature: 'Unprompted market takes, "we were modeling until 3am," wearing a Patagonia vest indoors',
  },
  {
    id: 'homeless_cs',
    name: 'Homeless CS Major',
    icon: '💻',
    description: 'Technically brilliant, socially unbothered, building in a library at 2am. Credentials optional.',
    cluster: 'tech',
    behaviorSignature: 'Zero pretense, brutally precise, ships first and asks for forgiveness later',
  },
  {
    id: 'startup_billionaire',
    name: 'Startup Billionaire',
    icon: '🚀',
    description: 'Post-exit founder. Still drives a Prius. Casually mentions the cap table like it\'s weather.',
    cluster: 'finance',
    behaviorSignature: 'Post-hustle serenity, wealth-adjacent humility, speaking in outcomes not amounts',
  },
  {
    id: 'liberal_arts',
    name: 'Liberal Arts Core',
    icon: '📚',
    description: 'Every conversation is a seminar. Has read Foucault. Will bring it up.',
    cluster: 'culture',
    behaviorSignature: 'Deconstructing your thesis before you finish it, citing critical theory unprompted, "we need to problematize that"',
  },
  {
    id: 'ai_founder',
    name: 'AI Founder',
    icon: '🤖',
    description: 'Building "the AI layer for everything." Genuinely has opinions about inference costs at 2am.',
    cluster: 'tech',
    behaviorSignature: 'Infrastructure framing for everything, "the wave is already here," vague technical depth delivered with full conviction',
  },
  {
    id: 'stanford_dropout',
    name: 'Stanford Dropout Energy',
    icon: '🌀',
    description: 'Left school to build something. Can\'t explain exactly when. The mystique is the strategy.',
    cluster: 'tech',
    behaviorSignature: 'Permanent gap year energy, "I was deep in a build," never explains the timeline, credentials are mid anyway',
  },
  {
    id: 'consulting_clone',
    name: 'Consulting Clone',
    icon: '📊',
    description: 'Thinks in frameworks. Speaks in deliverables. Has a 2x2 for your personality.',
    cluster: 'corporate',
    behaviorSignature: 'Circling back to align on key takeaways, structuring casual conversations as workstreams, the deck is always almost ready',
  },
  {
    id: 'crypto_philosopher',
    name: 'Crypto Philosopher',
    icon: '⛓️',
    description: 'Everything is a coordination problem. Banks are obsolete. Has a cold wallet and opinions.',
    cluster: 'wild',
    behaviorSignature: 'Trustless systems as the only solution, "the blockchain doesn\'t lie," bringing up exit strategies for nation-states',
  },
  {
    id: 'pm_newsletter',
    name: 'PM With a Newsletter',
    icon: '📝',
    description: 'Writes 3,000-word Substack posts about what product management taught them about grief.',
    cluster: 'corporate',
    behaviorSignature: 'Applying product frameworks to human relationships, "the user in this case is my therapist," the newsletter plug is always coming',
  },
  {
    id: 'vc_intern',
    name: 'VC Intern With Delusions',
    icon: '🔭',
    description: 'Drops fund names like they\'re confetti. Calls every person they meet a "founder to watch."',
    cluster: 'finance',
    behaviorSignature: 'GP namedropping, "I\'m doing a bit of diligence on this space," treating coffee chats as due diligence calls',
  },
  {
    id: 'student_athlete',
    name: 'Student Athlete',
    icon: '🏆',
    description: 'Wakes up at 5am voluntarily. Everything is a team sport. Disturbingly self-assured.',
    cluster: 'wild',
    behaviorSignature: '"I\'ve been competing at the highest level my whole life," sports metaphors for every work scenario, ice baths mentioned unprompted',
  },
  {
    id: 'performative_uni',
    name: 'Performative Uni Student',
    icon: '🎓',
    description: 'President of four clubs. Calls it "impact." It\'s the resume. It\'s always the resume.',
    cluster: 'culture',
    behaviorSignature: 'Club leadership in everything, "I\'m really passionate about creating change," optimizing optics with zero time for outcomes',
  },
]

export const PERSONA_MAP = new Map(PERSONAS.map(p => [p.id, p]))
