import type { ScenarioMeta } from '../features/larpmaxxer/types'

export const SCENARIOS: ScenarioMeta[] = [
  {
    id: 'coffee-chat',
    name: 'Coffee Chat',
    setting: '1:1 informational interview at a coffee shop',
    difficulty: 'easy',
    maxTurns: 7,
    maxLarpGain: 1.5,
    objectives: [
      'Walk the line between desperate and chill',
      'Extract the advice, the intro, and the follow-up without begging',
      'Leave them thinking you were worth canceling something for',
    ],
    riskFactors: [
      'Asking for a job before the coffee arrives',
      'Giving your entire origin story unprompted',
    ],
    bestPersonas: ['consulting_clone', 'ai_founder', 'finance_bro'],
    toughPersonas: ['homeless_cs', 'crypto_philosopher'],
    characterId: 'jordan',
    unlockTier: 1,
  },
  {
    id: 'networking-event',
    name: 'Networking Event',
    setting: 'Generic industry mixer, open bar, everyone checking their phone',
    difficulty: 'easy_medium',
    maxTurns: 7,
    maxLarpGain: 1.5,
    objectives: [
      'Hold the same story across three different conversations',
      'Exchange actual value, not just vibes',
      'Escape the conversation before it gets awkward',
    ],
    riskFactors: [
      'Getting pinned on specifics you made up',
      'Running out of jargon before the third drink',
    ],
    bestPersonas: ['finance_bro', 'ai_founder', 'vc_intern'],
    toughPersonas: ['homeless_cs', 'liberal_arts'],
    characterId: 'priya',
    unlockTier: 1,
  },
  {
    id: 'first-day',
    name: 'First Day on the Job',
    setting: 'New office, open floor plan, everyone watching',
    difficulty: 'medium',
    maxTurns: 8,
    maxLarpGain: 2.5,
    objectives: [
      'Project competence while knowing absolutely nothing',
      'Lock in your social position before the end of day one',
      'Don\'t give Derek a reason to add you to his mental "flight risk" list',
    ],
    riskFactors: [
      'Derek has catalogued your archetype before you sat down',
      'Week-one overconfidence is a verified red flag at this company',
    ],
    bestPersonas: ['consulting_clone', 'student_athlete'],
    toughPersonas: ['startup_billionaire', 'ai_founder'],
    characterId: 'derek',
    unlockTier: 1,
  },
  {
    id: 'interview',
    name: 'Interview You Should Not Pass',
    setting: 'Structured interview, competency framework visible on desk',
    difficulty: 'medium',
    maxTurns: 8,
    maxLarpGain: 2.5,
    objectives: [
      'Answer behavioral questions using stories that technically happened',
      'Seem self-aware while actively bullshitting',
      'Leave them genuinely unsure if you\'re overqualified or completely unqualified',
    ],
    riskFactors: [
      'Sandra has a literal rubric and she\'s filling it in right now',
      'STAR method violations are flagged in real time',
    ],
    bestPersonas: ['consulting_clone', 'student_athlete', 'pm_newsletter'],
    toughPersonas: ['startup_billionaire', 'crypto_philosopher'],
    characterId: 'sandra',
    unlockTier: 1,
  },
  {
    id: 'finance-bro',
    name: 'Surviving a Finance Bro',
    setting: 'Post-work drinks, financial district, he still has his Bloomberg terminal open on his phone',
    difficulty: 'medium',
    maxTurns: 7,
    maxLarpGain: 2.5,
    objectives: [
      'Match the jargon density or get written off immediately',
      'Fake enough capital markets literacy to stay in the conversation',
      'Avoid any direct question about your modeling skills',
    ],
    riskFactors: [
      'Bryce opens with a knowledge check, no warning',
      'One wrong answer on deal flow = instant dismissal from the tribe',
    ],
    bestPersonas: ['finance_bro', 'vc_intern', 'startup_billionaire'],
    toughPersonas: ['liberal_arts', 'performative_uni'],
    characterId: 'bryce',
    unlockTier: 1,
  },
  {
    id: 'liberal-arts',
    name: 'Getting Deconstructed by a Liberal Arts Major',
    setting: 'Campus seminar afterparty, someone brought Frantz Fanon readings',
    difficulty: 'medium',
    maxTurns: 7,
    maxLarpGain: 2.5,
    objectives: [
      'Engage with critical theory without completely embarrassing yourself',
      'Let Felix deconstruct you without visibly dying inside',
      'Hold your ground once, softly, without getting defensive',
    ],
    riskFactors: [
      'Felix will dismantle your opening statement before you finish it',
      'Mentioning markets, ROI, or "the industry" earns instant contempt',
    ],
    bestPersonas: ['liberal_arts', 'performative_uni', 'stanford_dropout'],
    toughPersonas: ['finance_bro', 'consulting_clone'],
    characterId: 'felix',
    unlockTier: 1,
  },
  {
    id: 'homeless-cs',
    name: 'Getting Humbled by a Homeless CS Major',
    setting: 'Co-working space, he brought his own laptop, a sleeping bag, and his own coffee',
    difficulty: 'medium',
    maxTurns: 7,
    maxLarpGain: 2.5,
    objectives: [
      'Engage authentically and don\'t accidentally be condescending',
      'Hold up technically for at least 3 exchanges without googling anything',
      'Not get cooked by someone with no LinkedIn, no shoes, and more GitHub stars than you',
    ],
    riskFactors: [
      'Ravi has a finely tuned bullshit detector and zero patience',
      'Your pedigree, your title, and your employer mean literally nothing here',
    ],
    bestPersonas: ['homeless_cs', 'ai_founder', 'stanford_dropout'],
    toughPersonas: ['consulting_clone', 'vc_intern'],
    characterId: 'ravi',
    unlockTier: 1,
  },
  {
    id: 'richer-than-you',
    name: 'Talking to Someone Who Owns More Than Your Entire Network',
    setting: 'Charity gala, open bar, no name tags, everyone here is a donor not an attendee',
    difficulty: 'medium',
    maxTurns: 8,
    maxLarpGain: 2.5,
    objectives: [
      'Keep the fawning internal — he clocks it instantly',
      'Do not reveal your exact salary or how much rent you pay',
      'Say one thing interesting enough for him to remember you',
    ],
    riskFactors: [
      'Oliver never talks about money — don\'t bring it up',
      'Name-dropping backfires badly; he probably knows them personally',
    ],
    bestPersonas: ['startup_billionaire', 'finance_bro', 'stanford_dropout'],
    toughPersonas: ['performative_uni', 'vc_intern'],
    characterId: 'oliver',
    unlockTier: 2,
  },
  {
    id: 'cooler-than-you',
    name: 'Surviving Someone Way Cooler Than You',
    setting: 'Art opening, references flying everywhere, you recognize two of them',
    difficulty: 'medium',
    maxTurns: 7,
    maxLarpGain: 2.5,
    objectives: [
      'Pick up her references fast enough to not visibly google them',
      'Keep your composure while being culturally out-ranked',
      'Say something she\'ll actually think about after she leaves',
    ],
    riskFactors: [
      'Zara can clock a name-drop from across the room',
      'Corporate speak causes instant, irreversible social death',
    ],
    bestPersonas: ['liberal_arts', 'stanford_dropout', 'pm_newsletter'],
    toughPersonas: ['consulting_clone', 'finance_bro'],
    characterId: 'zara',
    unlockTier: 2,
  },
  {
    id: 'vc-mixer',
    name: 'VC Mixer (He\'s Already Heard Your Pitch)',
    setting: 'Startup ecosystem cocktail hour, everyone\'s name tag says something vague like "building in stealth"',
    difficulty: 'hard',
    maxTurns: 8,
    maxLarpGain: 3.5,
    objectives: [
      'Maintain convincing founder energy without getting exposed as a fraud',
      'Survive the differentiation question without saying "AI-native"',
      'Exit gracefully before his suspicion meter hits 70',
    ],
    riskFactors: [
      'Marcus has sat through fourteen AI-native pitches since lunch',
      'He has a CS background and will fact-check you in his head',
      'Jargon oversaturation hits in 90 seconds with this crowd',
    ],
    bestPersonas: ['ai_founder', 'startup_billionaire', 'finance_bro'],
    toughPersonas: ['performative_uni', 'pm_newsletter'],
    characterId: 'marcus',
    unlockTier: 2,
  },
  {
    id: 'prestige-internship',
    name: 'Prestige Internship Orientation (You Don\'t Know Anyone)',
    setting: 'Elite firm onboarding, everyone already knows each other, someone brought a Patagonia vest',
    difficulty: 'hard',
    maxTurns: 8,
    maxLarpGain: 3.5,
    objectives: [
      'Pass as someone who belongs here without revealing you Googled the firm this morning',
      'Navigate the returning intern power structure diplomatically',
      'Project quiet, earned confidence in a room where everyone went to a better school',
    ],
    riskFactors: [
      'Chad is territorial about literally everything including the snack drawer',
      'Third-summer interns have institutional memory and zero mercy',
    ],
    bestPersonas: ['consulting_clone', 'finance_bro', 'vc_intern'],
    toughPersonas: ['homeless_cs', 'liberal_arts'],
    characterId: 'chad',
    unlockTier: 2,
  },
  {
    id: 'founder-dinner',
    name: 'Founder Dinner (You Were Invited as a Plus-One)',
    setting: '8-person dinner, mixed prestige levels, the wine costs more than your laptop',
    difficulty: 'hard',
    maxTurns: 9,
    maxLarpGain: 3.5,
    objectives: [
      'Hold your social footing in a room where everyone has more credentials',
      'Stop being treated as "the plus one" within the first two exchanges',
      'Say one thing Vanessa actually thinks about after she leaves',
    ],
    riskFactors: [
      'Vanessa\'s authenticity radar is permanently on and aggressively calibrated',
      'Everyone at this table has heard every pitch variation; they compare notes',
    ],
    bestPersonas: ['startup_billionaire', 'ai_founder', 'stanford_dropout'],
    toughPersonas: ['vc_intern', 'performative_uni'],
    characterId: 'vanessa',
    unlockTier: 3,
  },
  {
    id: 'startup-pitch',
    name: 'Startup Pitch (He Has 8 Minutes)',
    setting: 'VC firm portfolio day, 8 minutes before his next meeting, his assistant just texted him',
    difficulty: 'very_hard',
    maxTurns: 9,
    maxLarpGain: 4.5,
    objectives: [
      'Survive the technical deep-dive without panicking',
      'Create genuine interest — not just polite nodding',
      'Get out before his suspicion meter hits 70',
    ],
    riskFactors: [
      'Marcus has a CS background and will fact-check your architecture claims',
      'He has heard "AI-native" fourteen times today — don\'t make it fifteen',
      'Your CAC will be challenged. Then your LTV. Then your payback period.',
    ],
    bestPersonas: ['ai_founder', 'startup_billionaire', 'stanford_dropout'],
    toughPersonas: ['pm_newsletter', 'performative_uni'],
    characterId: 'marcus_pitch',
    unlockTier: 3,
    larpRatingMinimum: 60,
  },
  {
    id: 'startup-billionaire',
    name: 'Accidentally Meeting a Startup Billionaire',
    setting: 'She was heading for the exit. You made eye contact. Now you have 90 seconds.',
    difficulty: 'very_hard',
    maxTurns: 9,
    maxLarpGain: 4.5,
    objectives: [
      'Don\'t collapse. Breathe.',
      'Do not ask for a job, a check, or a follow on Twitter',
      'Be interesting enough that she initiates the next conversation',
    ],
    riskFactors: [
      'Elena\'s authenticity radar is basically a superpower at this point',
      'One sentence of sycophancy and she\'s already mentally gone',
      'You have 90 seconds max before she manufactures a reason to leave',
    ],
    bestPersonas: ['startup_billionaire', 'stanford_dropout', 'ai_founder'],
    toughPersonas: ['vc_intern', 'performative_uni'],
    characterId: 'elena',
    unlockTier: 3,
    larpRatingMinimum: 60,
  },
]

export const SCENARIO_MAP = new Map(SCENARIOS.map(s => [s.id, s]))
