import type { ScenarioContent } from '../../features/larpmaxxer/types'

export const scenarioContent: ScenarioContent = {
  scenarioId: 'founder-dinner',
  briefDescription:
    "Vanessa is three months from IPO and has spent seven years developing an immunity to bullshit. She's drinking the good wine, she's paying for it, and she has zero patience for people at this table who are performing a version of themselves.",
  openingLine:
    "Okay, let's skip the titles. What do you actually do — and I mean the thing that would stop happening if you stopped showing up.",
  dialogueNodes: [
    {
      turn: 1,
      characterLine:
        "Okay. Is that the thing that matters most to you right now, or is that just the current vehicle?",
      options: [
        {
          id: 'fnd-t1-a',
          personaTag: 'startup_billionaire',
          text: "Both, honestly. The vehicle and the thing aren't separable at this point — I've been working on versions of this problem for six years. I can't tell where the obsession ends and the company starts. That might be a feature or a bug depending on the outcome.",
          flavorBadge: 'authentic',
          metricDeltas: { aura: 14, socialFooting: 6, plausibility: 5, larpContinuity: 5, respect: 8 },
          meterDeltas: { impressed: 14, suspicion: -7 },
          characterThinks: "He named the ambiguity between obsession and strategy. That's the most honest thing I've heard at a founder dinner in two years.",
        },
        {
          id: 'fnd-t1-b',
          personaTag: 'ai_founder',
          text: "The problem is what matters to me. The company is the most efficient container I could find for making progress on it. If a better container existed I'd use that instead.",
          flavorBadge: 'alpha',
          metricDeltas: { aura: 13, socialFooting: 5, plausibility: 5, larpContinuity: 4, respect: 7 },
          meterDeltas: { impressed: 13, suspicion: -6 },
          characterThinks: "He separated problem from company. That's a disciplined founder answer. I've asked this question 30 times and I've never heard it framed this cleanly.",
        },
        {
          id: 'fnd-t1-c',
          personaTag: 'stanford_dropout',
          text: "Current vehicle — but a well-chosen one. I'm building toward a specific capability and this company is the path I've found. If the path closes I'd find another one. The goal doesn't depend on this specific attempt.",
          flavorBadge: 'calculated',
          metricDeltas: { aura: 9, socialFooting: 4, plausibility: 3, larpContinuity: 3, respect: 5 },
          meterDeltas: { impressed: 8, suspicion: 3 },
          characterThinks: "He called it a vehicle without apology and has a second path ready. That's either emotional detachment or exceptional intellectual clarity. I want to know which.",
        },
        {
          id: 'fnd-t1-d',
          personaTag: 'vc_intern',
          text: "I'd say both — I'm really passionate about what we're building and I think the mission and the execution are aligned in a way that makes the work feel meaningful rather than just instrumental.",
          flavorBadge: 'glazed',
          metricDeltas: { aura: 1, socialFooting: 0, plausibility: 0, larpContinuity: -1, respect: -1 },
          meterDeltas: { impressed: 0, suspicion: 9 },
          characterThinks: "He said 'passionate' and 'aligned' and 'meaningful.' I've heard those words so many times they've stopped meaning anything.",
        },
        {
          id: 'fnd-t1-e',
          personaTag: 'performative_uni',
          text: "It's definitely the thing that matters most — I think if you're not totally committed to the vision at this stage then you're not going to push through the hard parts. The mission is what sustains you when everything else is falling apart.",
          flavorBadge: 'cringe_risk',
          metricDeltas: { aura: -2, socialFooting: -1, plausibility: -2, larpContinuity: -2, respect: -2 },
          meterDeltas: { impressed: -1, suspicion: 10 },
          characterThinks: "He described founding as sustained by 'the mission.' That's a LinkedIn bio, not an answer.",
        },
      ],
    },
    {
      turn: 2,
      characterLine:
        "Everyone at this table has built something. The question I'm more interested in is what you've gotten wrong — specifically what you believed at the start that turned out to be false.",
      options: [
        {
          id: 'fnd-t2-a',
          personaTag: 'startup_billionaire',
          text: "I believed the product would sell itself to the right buyer — that clear value would create obvious pull. What I got wrong is that enterprise buyers don't buy on clarity, they buy on confidence, and confidence is social, not analytical. I wasted a year making better demos for people who needed better social proof.",
          flavorBadge: 'authentic',
          metricDeltas: { aura: 15, socialFooting: 6, plausibility: 5, larpContinuity: 5, respect: 9 },
          meterDeltas: { impressed: 15, suspicion: -8 },
          characterThinks: "He named a cognitive model he had wrong, explained the mechanism of the error, and quantified the cost. That's operational self-awareness at the right resolution.",
        },
        {
          id: 'fnd-t2-b',
          personaTag: 'ai_founder',
          text: "I thought the technical differentiation was the moat. It took 18 months to realize that the technical edge has a 12-month half-life in this market and the real moat was workflow integration depth. By the time I understood the right thing to build, I'd funded the wrong thing.",
          flavorBadge: 'prestige',
          metricDeltas: { aura: 14, socialFooting: 6, plausibility: 5, larpContinuity: 5, respect: 8 },
          meterDeltas: { impressed: 14, suspicion: -6 },
          characterThinks: "He named the half-life of his own technical edge and recalibrated. That's the kind of honesty that makes founders actually improve.",
        },
        {
          id: 'fnd-t2-c',
          personaTag: 'stanford_dropout',
          text: "I thought hiring smart generalists would scale better than hiring narrow specialists. What actually happened is that generalists are excellent at inventing the right solution and terrible at replicating it. We wasted six months on processes that only worked when the person who invented them was in the room.",
          flavorBadge: 'alpha',
          metricDeltas: { aura: 12, socialFooting: 5, plausibility: 4, larpContinuity: 4, respect: 7 },
          meterDeltas: { impressed: 12, suspicion: -4 },
          characterThinks: "The generalist-versus-specialist failure mode is real and he articulated it precisely. I made the same mistake. I respect the honesty.",
        },
        {
          id: 'fnd-t2-d',
          personaTag: 'consulting_clone',
          text: "I thought the market was more educated about the problem than it was. We built for sophisticated buyers and found out most of our prospects were earlier in their understanding than we assumed. The sales cycle was twice as long as projected because we were teaching, not selling.",
          flavorBadge: 'calculated',
          metricDeltas: { aura: 8, socialFooting: 3, plausibility: 3, larpContinuity: 3, respect: 5 },
          meterDeltas: { impressed: 7, suspicion: 3 },
          characterThinks: "Market sophistication misjudgment is a clean answer. Not as sharp as the first two but still a real mistake with a real mechanism.",
        },
        {
          id: 'fnd-t2-e',
          personaTag: 'performative_uni',
          text: "I underestimated how hard the cultural piece would be — I thought if you hired the right people the culture would emerge naturally. The lesson was that culture is a product you have to design and maintain intentionally.",
          flavorBadge: 'glazed',
          metricDeltas: { aura: 2, socialFooting: 1, plausibility: 1, larpContinuity: -1, respect: 1 },
          meterDeltas: { impressed: 1, suspicion: 8 },
          characterThinks: "'Culture is a product you design' is the thing every founder says in year two. It's a real lesson delivered in the dullest possible packaging.",
        },
      ],
    },
    {
      turn: 3,
      characterLine:
        "Good. Who was the hardest person you had to let go, and did you wait too long?",
      options: [
        {
          id: 'fnd-t3-a',
          personaTag: 'startup_billionaire',
          text: "My first VP of Sales. She was one of my earliest believers — closed our first 10 deals on nothing but conviction and a terrible demo. She couldn't scale past the 2M ARR milestone. I waited eight months too long because I felt I owed her. The company paid for that delay in two slow quarters.",
          flavorBadge: 'authentic',
          metricDeltas: { aura: 15, socialFooting: 6, plausibility: 5, larpContinuity: 5, respect: 10 },
          meterDeltas: { impressed: 15, suspicion: -9 },
          characterThinks: "Specific person, specific role, specific reason for delay, specific cost. That's the real answer to this question and it almost never sounds like that.",
        },
        {
          id: 'fnd-t3-b',
          personaTag: 'ai_founder',
          text: "My cofounder, year three. Not for bad reasons — for misalignment on what kind of company we were building. I wanted a category leader, he wanted a profitable acquisition target. You can't navigate that divergence with a quarterly check-in. Yes, I waited too long. By about six months.",
          flavorBadge: 'alpha',
          metricDeltas: { aura: 14, socialFooting: 5, plausibility: 5, larpContinuity: 5, respect: 9 },
          meterDeltas: { impressed: 14, suspicion: -7 },
          characterThinks: "He let go of his cofounder and owned the timeline of his delay. That's the hardest answer in the canon of founder questions and he gave it cleanly.",
        },
        {
          id: 'fnd-t3-c',
          personaTag: 'stanford_dropout',
          text: "A senior engineer who was individually excellent and organizationally toxic. The code shipped but the team around him stopped asking for help because asking meant being made to feel stupid. I waited until two junior hires told me they were considering leaving. Six months late, minimum.",
          flavorBadge: 'prestige',
          metricDeltas: { aura: 13, socialFooting: 5, plausibility: 4, larpContinuity: 4, respect: 8 },
          meterDeltas: { impressed: 12, suspicion: -5 },
          characterThinks: "Brilliant-but-toxic engineering archetype, told with enough specificity to be true. And yes, everyone waits too long on that person.",
        },
        {
          id: 'fnd-t3-d',
          personaTag: 'vc_intern',
          text: "An early employee who wasn't growing with the company. It was hard because he was one of the original team members and the relationship was more personal than professional. I did wait too long — I let the emotional relationship override the organizational reality.",
          flavorBadge: 'calculated',
          metricDeltas: { aura: 6, socialFooting: 3, plausibility: 3, larpContinuity: 2, respect: 4 },
          meterDeltas: { impressed: 5, suspicion: 5 },
          characterThinks: "He named the mechanism correctly but left the story anonymous and vague. The vagueness means he's either protecting someone or doesn't fully own it.",
        },
        {
          id: 'fnd-t3-e',
          personaTag: 'performative_uni',
          text: "It's a hard question — I've had to let people go and it's never easy. We try to be really thoughtful about how we do it so that people leave feeling respected even if the outcome is painful. Our offboarding process has actually gotten pretty good.",
          flavorBadge: 'cringe_risk',
          metricDeltas: { aura: -5, socialFooting: -3, plausibility: -4, larpContinuity: -4, respect: -4 },
          meterDeltas: { impressed: -5, suspicion: 14 },
          characterThinks: "I asked about the hardest person he let go and he told me his offboarding process is good. He's not ready for this table.",
        },
      ],
    },
    {
      turn: 4,
      characterLine:
        "The cofounder answer is the most honest thing anyone's said tonight. Let me push on something: how do you make decisions under genuine uncertainty — not the frameworks, the actual mechanism?",
      options: [
        {
          id: 'fnd-t4-a',
          personaTag: 'startup_billionaire',
          text: "I ask myself what I'd believe if the data came back opposite to what I expect. If reversing the data wouldn't change my view, I'm not actually reasoning from evidence — I'm looking for confirmation. That test catches about 40% of decisions where I think I'm being analytical but I'm actually just being fast.",
          flavorBadge: 'alpha',
          metricDeltas: { aura: 15, socialFooting: 6, plausibility: 5, larpContinuity: 5, respect: 9 },
          meterDeltas: { impressed: 15, suspicion: -8 },
          characterThinks: "He described a belief-inversion test for epistemic hygiene. That's the kind of thinking I look for in executives and almost never find.",
        },
        {
          id: 'fnd-t4-b',
          personaTag: 'ai_founder',
          text: "I force myself to name the one thing I'd need to see to change my mind before I make the decision. If I can't name it, I'm not in the decision space at all — I'm in a rationalizing space. Naming the reversing condition is the work.",
          flavorBadge: 'prestige',
          metricDeltas: { aura: 13, socialFooting: 5, plausibility: 5, larpContinuity: 4, respect: 8 },
          meterDeltas: { impressed: 13, suspicion: -6 },
          characterThinks: "Pre-mortem logic before the decision rather than after. That's a genuinely useful decision practice, not a framework answer.",
        },
        {
          id: 'fnd-t4-c',
          personaTag: 'stanford_dropout',
          text: "I talk to the person in my network who's most likely to disagree with me. Not to be convinced by them — to understand what evidence they have that I don't. My mental model updates by 15-20% from those conversations even when I don't change my ultimate decision.",
          flavorBadge: 'calculated',
          metricDeltas: { aura: 10, socialFooting: 4, plausibility: 4, larpContinuity: 3, respect: 6 },
          meterDeltas: { impressed: 10, suspicion: -2 },
          characterThinks: "Adversarial information seeking with a calibrated update estimate. That's a real epistemic practice.",
        },
        {
          id: 'fnd-t4-d',
          personaTag: 'consulting_clone',
          text: "I sleep on it, run the structured process — second-order effects, pre-mortem, key assumptions list — and then make the call. The process doesn't give me the answer but it usually surfaces the thing I was trying not to think about.",
          flavorBadge: 'wildcard',
          metricDeltas: { aura: 5, socialFooting: 2, plausibility: 2, larpContinuity: 1, respect: 3 },
          meterDeltas: { impressed: 4, suspicion: 6 },
          characterThinks: "He said 'structured process' and listed the standard decision frameworks. That's a framework answer when I asked for a mechanism.",
        },
        {
          id: 'fnd-t4-e',
          personaTag: 'vc_intern',
          text: "I trust my gut more than I used to — I think pattern recognition from accumulated experience produces fast correct answers that analytical processes are too slow to replicate under real conditions. The gut is usually ahead of the spreadsheet.",
          flavorBadge: 'cringe_risk',
          metricDeltas: { aura: -3, socialFooting: -2, plausibility: -3, larpContinuity: -3, respect: -3 },
          meterDeltas: { impressed: -2, suspicion: 11 },
          characterThinks: "'Trust my gut' is the answer people give when they haven't built a decision practice and want to sound like they have.",
        },
      ],
    },
    {
      turn: 5,
      characterLine:
        "The belief-inversion test is genuinely useful. I'm stealing it. Tell me about your fundraising relationship — what does your lead investor not understand about what you're building?",
      options: [
        {
          id: 'fnd-t5-a',
          personaTag: 'startup_billionaire',
          text: "They think the enterprise motion is the endgame. I think the enterprise motion is the trojan horse and the real play is the platform layer that opens once we own enough of the workflow. They've funded what I told them — I just haven't told them the whole picture yet because I need the current milestone to make the next pitch credible.",
          flavorBadge: 'alpha',
          metricDeltas: { aura: 16, socialFooting: 5, plausibility: 4, larpContinuity: 5, respect: 9 },
          meterDeltas: { impressed: 15, suspicion: -7 },
          characterThinks: "He just told me he's managing his investor's information strategically. I've done the same thing. He's not wrong to do it. I'm going to want to know what the full picture is.",
        },
        {
          id: 'fnd-t5-b',
          personaTag: 'ai_founder',
          text: "They're modeling us as a tool company with a SaaS revenue model. I think we're building the infrastructure that the next generation of tools runs on. Those are different businesses with different outcomes and I haven't found the right moment to surface that misalignment.",
          flavorBadge: 'prestige',
          metricDeltas: { aura: 13, socialFooting: 5, plausibility: 4, larpContinuity: 4, respect: 8 },
          meterDeltas: { impressed: 13, suspicion: -5 },
          characterThinks: "Tool versus infrastructure is a real strategic divergence with massive outcome implications. He's sitting on this at the board level and managing it carefully.",
        },
        {
          id: 'fnd-t5-c',
          personaTag: 'stanford_dropout',
          text: "They don't fully understand why the international expansion thesis is wrong for us right now. They're mapping our trajectory to a portfolio company that went international at this ARR and it worked. Our ICP doesn't translate. I've pushed back twice and lost both times.",
          flavorBadge: 'calculated',
          metricDeltas: { aura: 9, socialFooting: 4, plausibility: 4, larpContinuity: 3, respect: 6 },
          meterDeltas: { impressed: 9, suspicion: -1 },
          characterThinks: "He named a specific strategic disagreement with his board and quantified how many times he's lost it. That's honest governance disclosure at a dinner table.",
        },
        {
          id: 'fnd-t5-d',
          personaTag: 'consulting_clone',
          text: "They're more focused on the revenue growth curve than the retention quality. My lead investor wants to see the ARR chart inflect; I care more about the NRR and cohort behavior because that's what tells me whether the product is actually working.",
          flavorBadge: 'wildcard',
          metricDeltas: { aura: 7, socialFooting: 3, plausibility: 3, larpContinuity: 2, respect: 4 },
          meterDeltas: { impressed: 6, suspicion: 4 },
          characterThinks: "ARR-versus-NRR priority divergence is a real tension. He's right that NRR is the more honest signal. The disagreement is legitimate.",
        },
        {
          id: 'fnd-t5-e',
          personaTag: 'vc_intern',
          text: "Honestly I think we're pretty aligned — they've been very supportive and I feel like they understand the vision. The relationship has been really positive so far.",
          flavorBadge: 'cringe_risk',
          metricDeltas: { aura: -4, socialFooting: -3, plausibility: -4, larpContinuity: -4, respect: -4 },
          meterDeltas: { impressed: -4, suspicion: 14 },
          characterThinks: "He said his investors understand the vision and the relationship is positive. Every founder says that. None of them mean it. Or he means it, which is worse.",
        },
      ],
    },
    {
      turn: 6,
      characterLine:
        "I'm three months from IPO and I still get the information management problem. Let me ask you something more personal: what are you optimizing for beyond the company?",
      options: [
        {
          id: 'fnd-t6-a',
          personaTag: 'startup_billionaire',
          text: "Judgment, mainly. I want to finish this in a way that makes my next decision-making better, not just richer. The outcome I'm most afraid of isn't failure — it's success that doesn't teach me anything I didn't already know going in.",
          flavorBadge: 'authentic',
          metricDeltas: { aura: 15, socialFooting: 6, plausibility: 5, larpContinuity: 5, respect: 10 },
          meterDeltas: { impressed: 15, suspicion: -9 },
          characterThinks: "He said the outcome he fears most is uninstructive success. I've thought about exactly this for seven years and never said it out loud.",
        },
        {
          id: 'fnd-t6-b',
          personaTag: 'ai_founder',
          text: "I want to have solved a problem that's genuinely hard enough that my contribution matters in a way that persists. I'm not interested in optionality as an outcome — I want to know I built something that kept working after I stopped.",
          flavorBadge: 'alpha',
          metricDeltas: { aura: 14, socialFooting: 5, plausibility: 5, larpContinuity: 4, respect: 9 },
          meterDeltas: { impressed: 14, suspicion: -7 },
          characterThinks: "He described optionality as an insufficient outcome. That's a rare thing for a first-time founder to believe before they've had the exit. I want to know if he still believes it on the other side.",
        },
        {
          id: 'fnd-t6-c',
          personaTag: 'stanford_dropout',
          text: "The freedom to work on the next thing without financial constraint and with enough credibility that people take the next bet seriously. I'm building toward the conditions where the work I care most about is possible.",
          flavorBadge: 'calculated',
          metricDeltas: { aura: 9, socialFooting: 4, plausibility: 3, larpContinuity: 3, respect: 5 },
          meterDeltas: { impressed: 8, suspicion: 3 },
          characterThinks: "He's optimizing for the conditions of the next bet. That's a reasonable thing to optimize for. Not the most interesting answer at this table but an honest one.",
        },
        {
          id: 'fnd-t6-d',
          personaTag: 'crypto_philosopher',
          text: "I'm not sure the 'beyond the company' framing maps onto how I experience it — the company is embedded in the larger question I'm trying to answer, so I don't really have a personal goal that sits outside the work. That might be a problem I'll have to solve later.",
          flavorBadge: 'wildcard',
          metricDeltas: { aura: 7, socialFooting: 2, plausibility: 2, larpContinuity: 1, respect: 4 },
          meterDeltas: { impressed: 5, suspicion: 6 },
          characterThinks: "He said the personal and professional are inseparable and acknowledged that might be a future problem. That's honest in a way that makes me slightly worried for him.",
        },
        {
          id: 'fnd-t6-e',
          personaTag: 'performative_uni',
          text: "Impact, honestly. I want to know that what I built made a real difference for real people. The financial outcome matters but it's not what drives me on the hard days.",
          flavorBadge: 'cringe_risk',
          metricDeltas: { aura: -4, socialFooting: -2, plausibility: -3, larpContinuity: -3, respect: -3 },
          meterDeltas: { impressed: -3, suspicion: 12 },
          characterThinks: "He said 'impact' and 'real difference for real people.' I'm going to focus on my wine.",
        },
      ],
    },
    {
      turn: 7,
      characterLine:
        "The next thing question is interesting. Give me your honest read on the current market — not the narrative, what you actually see when you look at the data.",
      options: [
        {
          id: 'fnd-t7-a',
          personaTag: 'startup_billionaire',
          text: "I see a market where the AI budget exists but the deployment pipeline is broken. Everyone's bought the story, very few companies can point to a shipped system that their employees use every day. The gap between committed spend and realized value is going to produce a correction in 18 months that looks a lot like 2001 did for enterprise software.",
          flavorBadge: 'alpha',
          metricDeltas: { aura: 15, socialFooting: 6, plausibility: 5, larpContinuity: 5, respect: 9 },
          meterDeltas: { impressed: 15, suspicion: -8 },
          characterThinks: "He called a market correction with a specific mechanism and a historical analogy that isn't lazy. That's an informed market view, not a talking point.",
        },
        {
          id: 'fnd-t7-b',
          personaTag: 'ai_founder',
          text: "The infrastructure layer is two to three years behind where the application layer is growing. Founders are building on sand. The companies that will matter in five years are the ones solving for reliability and observability, not the ones with the best demo video.",
          flavorBadge: 'prestige',
          metricDeltas: { aura: 13, socialFooting: 5, plausibility: 4, larpContinuity: 4, respect: 8 },
          meterDeltas: { impressed: 13, suspicion: -6 },
          characterThinks: "Infrastructure lag argument is real and he named the implication without over-stating it.",
        },
        {
          id: 'fnd-t7-c',
          personaTag: 'stanford_dropout',
          text: "The market is bifurcating faster than people are acknowledging — the companies with genuine technical differentiation are getting stronger and the ones with distribution and marketing but weak product are getting weaker. The middle is disappearing. I think you want to be very clearly in the first category right now.",
          flavorBadge: 'calculated',
          metricDeltas: { aura: 10, socialFooting: 4, plausibility: 4, larpContinuity: 3, respect: 6 },
          meterDeltas: { impressed: 10, suspicion: -2 },
          characterThinks: "Market bifurcation argument with a position recommendation. Clean and probably correct.",
        },
        {
          id: 'fnd-t7-d',
          personaTag: 'finance_bro',
          text: "The multiples are compressing faster than most founders have updated their mental models. Companies that raised at 15x ARR in 2021 are going to need to grow into those valuations on fundamentals, not narrative. The refinancing risk is underestimated.",
          flavorBadge: 'wildcard',
          metricDeltas: { aura: 8, socialFooting: 3, plausibility: 3, larpContinuity: 2, respect: 5 },
          meterDeltas: { impressed: 7, suspicion: 4 },
          characterThinks: "He went to multiples compression and refinancing risk. That's a CFO's market read, not a founder's. He has a finance brain.",
        },
        {
          id: 'fnd-t7-e',
          personaTag: 'pm_newsletter',
          text: "I think the narrative is getting ahead of the fundamentals but I'm honestly not sure by how much — there's genuine transformation happening alongside the hype and it's hard to separate them from inside the market.",
          flavorBadge: 'glazed',
          metricDeltas: { aura: 2, socialFooting: 1, plausibility: 1, larpContinuity: -1, respect: 1 },
          meterDeltas: { impressed: 1, suspicion: 8 },
          characterThinks: "'Narrative ahead of fundamentals but hard to tell by how much' is the most hedged possible market view. It's technically not wrong and completely useless.",
        },
      ],
    },
    {
      turn: 8,
      characterLine:
        "The correction framing is exactly right — I saw it happening six months before anyone was saying it out loud. One more question and then the table needs me back: what would you do differently if you started over today with everything you know?",
      options: [
        {
          id: 'fnd-t8-a',
          personaTag: 'startup_billionaire',
          text: "Hire for organizational scale earlier. Not the team that can get to 5M ARR — the team that can get to 50M ARR from day one, even if I can't afford them at par. The talent ceiling you set in year one follows you for longer than any product decision you make.",
          flavorBadge: 'alpha',
          metricDeltas: { aura: 15, socialFooting: 6, plausibility: 5, larpContinuity: 5, respect: 9 },
          meterDeltas: { impressed: 14, suspicion: -7 },
          characterThinks: "He named the talent ceiling problem in year one as the root cause. That's the right layer of analysis.",
        },
        {
          id: 'fnd-t8-b',
          personaTag: 'ai_founder',
          text: "I'd spend the first six months talking to customers and zero months building. I built too early on a problem hypothesis that was 70% right. 70% right costs you 30% of your runway and 18 months of technical debt. First principles: listen before you build.",
          flavorBadge: 'prestige',
          metricDeltas: { aura: 14, socialFooting: 5, plausibility: 5, larpContinuity: 4, respect: 8 },
          meterDeltas: { impressed: 13, suspicion: -6 },
          characterThinks: "He quantified the cost of a 30% wrong hypothesis. That's a post-mortem insight that most founders don't surface until year three.",
        },
        {
          id: 'fnd-t8-c',
          personaTag: 'stanford_dropout',
          text: "Choose the cofounder more carefully and have the alignment conversation explicitly before you start. The things that surface as disagreements in year three were visible as incompatibilities in the first conversation — I just didn't treat them as disqualifying.",
          flavorBadge: 'calculated',
          metricDeltas: { aura: 11, socialFooting: 4, plausibility: 4, larpContinuity: 4, respect: 7 },
          meterDeltas: { impressed: 10, suspicion: -3 },
          characterThinks: "He said the year three cofounder conflict was already visible in the founding conversation. That's a real and painful admission.",
        },
        {
          id: 'fnd-t8-d',
          personaTag: 'consulting_clone',
          text: "Build the pricing architecture right the first time. We started with usage-based pricing to get early adoption and it created structural constraints that cost us eight months to unwind when we moved to seats. The commercial architecture is as important as the technical architecture.",
          flavorBadge: 'wildcard',
          metricDeltas: { aura: 8, socialFooting: 3, plausibility: 3, larpContinuity: 2, respect: 5 },
          meterDeltas: { impressed: 7, suspicion: 3 },
          characterThinks: "Commercial architecture as a parallel to technical architecture. That's a useful frame and a real operational mistake.",
        },
        {
          id: 'fnd-t8-e',
          personaTag: 'vc_intern',
          text: "Honestly, I'd be more patient. I think I rushed some decisions because I was afraid of moving slowly and the better path was to slow down and be more deliberate. Speed is overvalued at the early stage.",
          flavorBadge: 'cringe_risk',
          metricDeltas: { aura: -2, socialFooting: -1, plausibility: -2, larpContinuity: -2, respect: -2 },
          meterDeltas: { impressed: -1, suspicion: 10 },
          characterThinks: "'Be more patient' is not a lesson, it's a mood. I asked what they'd do differently and they described an emotional state.",
        },
      ],
    },
    {
      turn: 9,
      characterLine:
        "The talent ceiling insight is the one that took me the longest to learn. Okay — last thing before I go back to the table. Why should I stay in touch with you specifically? Not why you'd benefit — why do I?",
      options: [
        {
          id: 'fnd-t9-a',
          personaTag: 'startup_billionaire',
          text: "Because I'm building in the space that's going to hit the inflection point you're describing — the deployment gap — and I'll know when it breaks before most people do. You might want that signal. And I'll call you when I have it, not when I need something.",
          flavorBadge: 'alpha',
          metricDeltas: { aura: 16, socialFooting: 7, plausibility: 5, larpContinuity: 5, respect: 10 },
          meterDeltas: { impressed: 16, suspicion: -10 },
          characterThinks: "He offered me market signal and specified that he'd call when he had information, not when he needed something. That is exactly the right answer to exactly this question. I'm giving him my direct number.",
        },
        {
          id: 'fnd-t9-b',
          personaTag: 'ai_founder',
          text: "Honest answer: I'm not sure yet. I think the conversation we'd have in 18 months will be more useful to you than any I could offer today — I'll know more and have harder questions. But if you have a problem in the space I'm in, I'm probably the cheapest honest opinion you can find.",
          flavorBadge: 'prestige',
          metricDeltas: { aura: 14, socialFooting: 6, plausibility: 5, larpContinuity: 4, respect: 9 },
          meterDeltas: { impressed: 14, suspicion: -7 },
          characterThinks: "He told me he doesn't know yet and offered the honest cheap opinion rather than a confident pitch. That kind of honesty from someone who clearly has calibrated intelligence is the answer.",
        },
        {
          id: 'fnd-t9-c',
          personaTag: 'stanford_dropout',
          text: "I have a point of view on where the market is going that diverges from the consensus you're probably hearing from everyone else at this table. Whether I'm right or wrong, the divergence is interesting information. And I'd rather give you the honest version than the shaped one.",
          flavorBadge: 'calculated',
          metricDeltas: { aura: 11, socialFooting: 5, plausibility: 4, larpContinuity: 4, respect: 7 },
          meterDeltas: { impressed: 11, suspicion: -4 },
          characterThinks: "He offered divergent signal as the value proposition. That's correct. Consensus is free. Divergence with reasoning is expensive.",
        },
        {
          id: 'fnd-t9-d',
          personaTag: 'crypto_philosopher',
          text: "I'm going to ask you questions nobody else will ask. Not because I'm trying to impress you — because I've been thinking about adjacent problems long enough that I have blind spots in opposite places to most people in this room.",
          flavorBadge: 'wildcard',
          metricDeltas: { aura: 9, socialFooting: 3, plausibility: 3, larpContinuity: 2, respect: 5 },
          meterDeltas: { impressed: 8, suspicion: 5 },
          characterThinks: "He offered complementary blind spots as the value. Unusual answer. Might be true.",
        },
        {
          id: 'fnd-t9-e',
          personaTag: 'performative_uni',
          text: "I'd love to stay connected — I've really valued this conversation and I think there's a lot we could learn from each other. I admire what you've built and I think your perspective would be really valuable for me.",
          flavorBadge: 'cringe_risk',
          metricDeltas: { aura: -5, socialFooting: -4, plausibility: -4, larpContinuity: -5, respect: -5 },
          meterDeltas: { impressed: -5, suspicion: 16 },
          characterThinks: "I asked why I should stay in touch with him. He told me why he should stay in touch with me. I've been in this business for 11 years and I still occasionally have to hide my face.",
        },
      ],
    },
  ],
}
