import type { ScenarioContent } from '../../features/larpmaxxer/types'

export const scenarioContent: ScenarioContent = {
  scenarioId: 'homeless-cs',
  briefDescription:
    'Ravi dropped out of Stanford after freshman year, has been building in public for 14 months, has 23,000 Twitter followers who watch him ship features in real time, and has not had a genuine non-technical conversation since August. He will respect exactly one thing: shipping.',
  openingLine:
    "— still staring at his screen — What are you actually building?",
  dialogueNodes: [
    {
      turn: 1,
      characterLine:
        "Okay. What's the stack? And how long have you been working on it?",
      options: [
        {
          id: 'hc-t1-a',
          personaTag: 'homeless_cs',
          text: "Next.js frontend, Postgres, deployed on Railway. Been at it six weeks. I had a working prototype in week two but the auth was wrong so I scrapped it and rebuilt from scratch.",
          flavorBadge: 'prestige',
          metricDeltas: { aura: 14, socialFooting: 6, plausibility: 5, larpContinuity: 5, respect: 8 },
          meterDeltas: { impressed: 14, suspicion: -7 },
          characterThinks: "Specific stack, specific timeline, scrapped and rebuilt auth. He's real.",
        },
        {
          id: 'hc-t1-b',
          personaTag: 'ai_founder',
          text: "Python backend, FastAPI, Pinecone for the vector store, React frontend. Three months in. The RAG pipeline is solid but the frontend is embarrassing — I keep telling myself I'll fix it and then building more backend instead.",
          flavorBadge: 'ambitious',
          metricDeltas: { aura: 12, socialFooting: 5, plausibility: 5, larpContinuity: 4, respect: 7 },
          meterDeltas: { impressed: 12, suspicion: -5 },
          characterThinks: "Real stack, honest about the embarrassing frontend, has a RAG pipeline that's working. This is a person.",
        },
        {
          id: 'hc-t1-c',
          personaTag: 'startup_billionaire',
          text: "We're still in the early stages — I'm working with a technical co-founder on architecture decisions. I'm more on the product and vision side, handling the go-to-market strategy while he handles the engineering.",
          flavorBadge: 'cringe_risk',
          metricDeltas: { aura: -4, socialFooting: -3, plausibility: -2, larpContinuity: -4, respect: -3 },
          meterDeltas: { impressed: -4, suspicion: 13 },
          characterThinks: "'Product and vision side.' He can't answer a tech question. Moving on.",
        },
        {
          id: 'hc-t1-d',
          personaTag: 'consulting_clone',
          text: "I'm working on a B2B SaaS product — I've been doing a lot of customer discovery first to make sure I'm building something people actually want before I commit to a specific technical architecture.",
          flavorBadge: 'glazed',
          metricDeltas: { aura: 1, socialFooting: -1, plausibility: 0, larpContinuity: -2, respect: -1 },
          meterDeltas: { impressed: -1, suspicion: 8 },
          characterThinks: "Customer discovery before architecture. He doesn't have a stack. I asked what the stack was.",
        },
        {
          id: 'hc-t1-e',
          personaTag: 'vc_intern',
          text: "I've been exploring the space and doing a lot of research — I have a clear thesis but I'm still in the ideation phase. I want to make sure I find the right problem before I start building anything.",
          flavorBadge: 'wildcard',
          metricDeltas: { aura: -5, socialFooting: -4, plausibility: -3, larpContinuity: -5, respect: -4 },
          meterDeltas: { impressed: -5, suspicion: 14 },
          characterThinks: "He's in the 'ideation phase.' He doesn't exist as a builder. This conversation is over.",
        },
      ],
    },
    {
      turn: 2,
      characterLine:
        "Railway's fine. Why'd you scrap the auth — what specifically was wrong with it?",
      options: [
        {
          id: 'hc-t2-a',
          personaTag: 'homeless_cs',
          text: "I'd rolled my own JWT implementation and the refresh token logic was broken in a way I didn't catch until I had two users logged in simultaneously. Once I saw the session collision I knew the whole thing was wrong and using NextAuth was just faster than fixing it.",
          flavorBadge: 'prestige',
          metricDeltas: { aura: 14, socialFooting: 6, plausibility: 5, larpContinuity: 5, respect: 8 },
          meterDeltas: { impressed: 14, suspicion: -8 },
          characterThinks: "Session collision on concurrent logins, moved to NextAuth. He debugged the specific failure mode and made the right call.",
        },
        {
          id: 'hc-t2-b',
          personaTag: 'ai_founder',
          text: "The token expiry logic was wrong and I was handling the edge case badly on the client side. I could have patched it but I decided to use Supabase Auth instead because the whole thing felt like something I shouldn't be owning at this stage.",
          flavorBadge: 'calculated',
          metricDeltas: { aura: 11, socialFooting: 4, plausibility: 5, larpContinuity: 4, respect: 7 },
          meterDeltas: { impressed: 11, suspicion: -4 },
          characterThinks: "Wrong edge case on token expiry, moved to Supabase. Good triage decision and right call on not owning auth.",
        },
        {
          id: 'hc-t2-c',
          personaTag: 'startup_billionaire',
          text: "Honestly I realized I was spending too much time on infrastructure and not enough on the core product. Auth is solved — I switched to Clerk and moved on.",
          flavorBadge: 'authentic',
          metricDeltas: { aura: 7, socialFooting: 3, plausibility: 4, larpContinuity: 3, respect: 4 },
          meterDeltas: { impressed: 6, suspicion: 2 },
          characterThinks: "Correct prioritization, moved to Clerk. Didn't diagnose the specific bug but made the right move.",
        },
        {
          id: 'hc-t2-d',
          personaTag: 'consulting_clone',
          text: "I was using a library that had a security vulnerability that got disclosed — I patched it but realized the whole auth pattern was wrong for what I needed and it was faster to restart.",
          flavorBadge: 'wildcard',
          metricDeltas: { aura: 4, socialFooting: 1, plausibility: 3, larpContinuity: 2, respect: 2 },
          meterDeltas: { impressed: 3, suspicion: 4 },
          characterThinks: "CVE-driven rebuild. Plausible. Not as interesting as a debugging story.",
        },
        {
          id: 'hc-t2-e',
          personaTag: 'liberal_arts',
          text: "I found a tutorial online and followed it but then realized I didn't actually understand what the JWT was doing at a cryptographic level, which made me uncomfortable shipping it. So I took two weeks to understand it properly before rewriting.",
          flavorBadge: 'unhinged',
          metricDeltas: { aura: 5, socialFooting: 2, plausibility: 3, larpContinuity: 2, respect: 3 },
          meterDeltas: { impressed: 4, suspicion: 3 },
          characterThinks: "He took two weeks to understand JWT cryptography before shipping. Slightly over-engineered decision process but I respect the rigor.",
        },
      ],
    },
    {
      turn: 3,
      characterLine:
        "Yeah, rolling your own auth is a trap. — glances up briefly — Do you have users?",
      options: [
        {
          id: 'hc-t3-a',
          personaTag: 'homeless_cs',
          text: "43 signups, 8 who have used it more than once. I know who each of them is. The 8 active ones are the only numbers I care about right now.",
          flavorBadge: 'prestige',
          metricDeltas: { aura: 15, socialFooting: 6, plausibility: 5, larpContinuity: 5, respect: 9 },
          meterDeltas: { impressed: 15, suspicion: -8 },
          characterThinks: "43 signups, 8 actives, knows each of them. That's the exact right answer and the exact right level of obsession.",
        },
        {
          id: 'hc-t3-b',
          personaTag: 'ai_founder',
          text: "12 beta users from my Twitter following. Engagement is uneven but two of them have been in almost every day for three weeks and one of them texted me about a bug at 11 PM. That's the signal I'm using to decide what to build next.",
          flavorBadge: 'ambitious',
          metricDeltas: { aura: 12, socialFooting: 5, plausibility: 5, larpContinuity: 4, respect: 7 },
          meterDeltas: { impressed: 12, suspicion: -5 },
          characterThinks: "12 betas, two engaged, one texting bugs at 11 PM. He's using the right retention signals.",
        },
        {
          id: 'hc-t3-c',
          personaTag: 'startup_billionaire',
          text: "We're in closed beta — I've been selective about who I let in because I want to control the early experience. We have 200 on the waitlist but only 15 in the product.",
          flavorBadge: 'calculated',
          metricDeltas: { aura: 7, socialFooting: 3, plausibility: 3, larpContinuity: 2, respect: 4 },
          meterDeltas: { impressed: 6, suspicion: 3 },
          characterThinks: "200 waitlist, 15 in. Waitlist is a vanity metric. 15 is the real number.",
        },
        {
          id: 'hc-t3-d',
          personaTag: 'pm_newsletter',
          text: "Not yet — I want to get to a point where I'm not embarrassed to show it before I let real users in. I'm probably two weeks from that.",
          flavorBadge: 'cringe_risk',
          metricDeltas: { aura: -3, socialFooting: -2, plausibility: -2, larpContinuity: -3, respect: -2 },
          meterDeltas: { impressed: -3, suspicion: 11 },
          characterThinks: "'Two weeks from not being embarrassed.' He has been saying that for two months, I guarantee it.",
        },
        {
          id: 'hc-t3-e',
          personaTag: 'vc_intern',
          text: "We're focusing on building the right product first before we do any acquisition — I don't want to get early users before the retention mechanism is solid.",
          flavorBadge: 'glazed',
          metricDeltas: { aura: -4, socialFooting: -3, plausibility: -2, larpContinuity: -4, respect: -3 },
          meterDeltas: { impressed: -4, suspicion: 12 },
          characterThinks: "No users. Waiting for the perfect product. Classic pre-launch trap. Hard pass.",
        },
      ],
    },
    {
      turn: 4,
      characterLine:
        "8 actives from 43 is actually good. — finally looks up — What's the thing that's currently most broken that you haven't fixed yet?",
      options: [
        {
          id: 'hc-t4-a',
          personaTag: 'homeless_cs',
          text: "The onboarding flow drops people off at step three at about 60% and I haven't fixed it because I'm not sure yet whether the drop-off is a UX problem or a product-market-fit signal. I don't want to optimize a funnel that's pointing at the wrong thing.",
          flavorBadge: 'prestige',
          metricDeltas: { aura: 15, socialFooting: 6, plausibility: 5, larpContinuity: 5, respect: 9 },
          meterDeltas: { impressed: 15, suspicion: -8 },
          characterThinks: "60% drop-off at step three, deliberately not fixed, correct diagnostic uncertainty about cause. That's mature product thinking.",
        },
        {
          id: 'hc-t4-b',
          personaTag: 'ai_founder',
          text: "The latency on the inference calls is bad — 4 to 7 seconds for a response — and I know it's because I'm doing synchronous calls in the wrong place, but fixing it means rearchitecting the job queue and I keep punting on it.",
          flavorBadge: 'ambitious',
          metricDeltas: { aura: 12, socialFooting: 5, plausibility: 5, larpContinuity: 4, respect: 7 },
          meterDeltas: { impressed: 12, suspicion: -5 },
          characterThinks: "4-7 second latency, knows the root cause is sync calls, punting on the job queue rearchitecture. He knows what's wrong and why he hasn't fixed it.",
        },
        {
          id: 'hc-t4-c',
          personaTag: 'startup_billionaire',
          text: "The dashboard UX is messy — it made sense when I built it but it doesn't reflect how users actually navigate. I have the designs but I haven't had time to implement them.",
          flavorBadge: 'calculated',
          metricDeltas: { aura: 7, socialFooting: 3, plausibility: 3, larpContinuity: 3, respect: 4 },
          meterDeltas: { impressed: 6, suspicion: 2 },
          characterThinks: "Messy dashboard, has redesigns unimplemented. Fine. Medium answer.",
        },
        {
          id: 'hc-t4-d',
          personaTag: 'pm_newsletter',
          text: "Honestly most things are working well — it's more that I have a list of features I want to build than bugs I need to fix. The core product is pretty solid at this point.",
          flavorBadge: 'cringe_risk',
          metricDeltas: { aura: -3, socialFooting: -2, plausibility: -2, larpContinuity: -3, respect: -2 },
          meterDeltas: { impressed: -3, suspicion: 10 },
          characterThinks: "'Core product is pretty solid.' 43 signups and 8 actives. That's a confident assessment.",
        },
        {
          id: 'hc-t4-e',
          personaTag: 'homeless_cs',
          text: "The billing integration is completely manual right now — I'm invoicing people over email and it's embarrassing. I know exactly how to implement Stripe, I've done it before, but I keep building features instead.",
          flavorBadge: 'authentic',
          metricDeltas: { aura: 9, socialFooting: 4, plausibility: 4, larpContinuity: 4, respect: 6 },
          meterDeltas: { impressed: 9, suspicion: -3 },
          characterThinks: "Manual billing over email, knows how to fix it, keeps building features instead. That's the right kind of honest.",
        },
      ],
    },
    {
      turn: 5,
      characterLine:
        "Not fixing it until you know whether it's UX or PMF is actually correct. Most people fix the funnel and miss the signal. — pauses typing — How are you funding this?",
      options: [
        {
          id: 'hc-t5-a',
          personaTag: 'homeless_cs',
          text: "I have three paying users. It's $300 a month right now and it covers hosting costs. I'm trying to get to ramen profitability before I think about anything else.",
          flavorBadge: 'prestige',
          metricDeltas: { aura: 14, socialFooting: 6, plausibility: 5, larpContinuity: 5, respect: 8 },
          meterDeltas: { impressed: 14, suspicion: -7 },
          characterThinks: "$300/month, covers hosting, targeting ramen profitability. He's in the right loop.",
        },
        {
          id: 'hc-t5-b',
          personaTag: 'stanford_dropout',
          text: "Savings from a six-month stint I did at a startup before I left. I have about $18K left, which gives me around eight months at my current burn. I'm not raising until I have something worth raising on.",
          flavorBadge: 'calculated',
          metricDeltas: { aura: 12, socialFooting: 5, plausibility: 5, larpContinuity: 4, respect: 7 },
          meterDeltas: { impressed: 12, suspicion: -5 },
          characterThinks: "Specific savings, specific runway calculation, not raising until it's worth it. Good discipline.",
        },
        {
          id: 'hc-t5-c',
          personaTag: 'vc_intern',
          text: "I've had a few VC conversations — there's some interest from a couple of pre-seed funds and I'm waiting to see if it materializes into something real.",
          flavorBadge: 'cringe_risk',
          metricDeltas: { aura: -3, socialFooting: -2, plausibility: -1, larpContinuity: -3, respect: -2 },
          meterDeltas: { impressed: -3, suspicion: 10 },
          characterThinks: "He's raising before he has users who pay. I'm done.",
        },
        {
          id: 'hc-t5-d',
          personaTag: 'startup_billionaire',
          text: "Personal runway from some previous work. I have about a year. I'm treating it like a job — 8 hours a day minimum, weekends when I'm in a build sprint.",
          flavorBadge: 'authentic',
          metricDeltas: { aura: 8, socialFooting: 3, plausibility: 4, larpContinuity: 3, respect: 5 },
          meterDeltas: { impressed: 7, suspicion: 2 },
          characterThinks: "Year of runway, treating it like a job. Solid setup. Nothing unusual.",
        },
        {
          id: 'hc-t5-e',
          personaTag: 'finance_bro',
          text: "I'm still contracting two days a week — it pays my rent and keeps me from having to make any compromises on the product direction. The overhead is worth it for the independence.",
          flavorBadge: 'wildcard',
          metricDeltas: { aura: 6, socialFooting: 3, plausibility: 4, larpContinuity: 2, respect: 4 },
          meterDeltas: { impressed: 5, suspicion: 2 },
          characterThinks: "Part-time contracting to protect product independence. Rational and honest.",
        },
      ],
    },
    {
      turn: 6,
      characterLine:
        "Ramen profitability is the right target. What does your day actually look like? Not aspirationally. Literally.",
      options: [
        {
          id: 'hc-t6-a',
          personaTag: 'homeless_cs',
          text: "Wake up at 8, coffee, check if anything broke overnight, do a 15-minute review of what I shipped yesterday and what went wrong, then block work until 1, eat something, talk to at least one user before 3, then build until I'm useless which is usually around 9 or 10. I tweet what I shipped before I sleep.",
          flavorBadge: 'prestige',
          metricDeltas: { aura: 14, socialFooting: 6, plausibility: 5, larpContinuity: 5, respect: 8 },
          meterDeltas: { impressed: 14, suspicion: -7 },
          characterThinks: "User call every day, shipped review every morning, tweets at night. That's a builder's life described accurately.",
        },
        {
          id: 'hc-t6-b',
          personaTag: 'ai_founder',
          text: "I work in three-hour blocks and track what I completed versus what I thought I'd complete. The ratio is pretty humbling. I have a daily note doc that's basically a real-time log — helps me see when I'm spinning versus moving.",
          flavorBadge: 'calculated',
          metricDeltas: { aura: 11, socialFooting: 4, plausibility: 4, larpContinuity: 4, respect: 6 },
          meterDeltas: { impressed: 11, suspicion: -4 },
          characterThinks: "Three-hour blocks, tracking completion rate versus projected. He measures his own output honestly.",
        },
        {
          id: 'hc-t6-c',
          personaTag: 'stanford_dropout',
          text: "Honestly? Inconsistent. Some days I'm in flow for 12 hours, some days I get distracted and barely ship anything. I've stopped judging the bad days and started tracking weekly output instead of daily — the weekly signal is more stable.",
          flavorBadge: 'authentic',
          metricDeltas: { aura: 9, socialFooting: 4, plausibility: 4, larpContinuity: 3, respect: 6 },
          meterDeltas: { impressed: 9, suspicion: -2 },
          characterThinks: "Honest about inconsistency, moved to weekly output measurement. Correct adjustment.",
        },
        {
          id: 'hc-t6-d',
          personaTag: 'pm_newsletter',
          text: "I have a pretty structured morning routine — journaling, meditation, then I plan my priorities for the day before I open my laptop. I find the pre-work rituals really set the tone for the day.",
          flavorBadge: 'cringe_risk',
          metricDeltas: { aura: -2, socialFooting: -1, plausibility: 1, larpContinuity: -2, respect: -1 },
          meterDeltas: { impressed: -2, suspicion: 9 },
          characterThinks: "Journaling and meditation before opening the laptop. He told me his morning routine. I asked what his day looks like.",
        },
        {
          id: 'hc-t6-e',
          personaTag: 'startup_billionaire',
          text: "Mostly I sit here until I can't solve the problem I'm working on and then I go for a walk and come back. I haven't figured out a good rhythm yet — I'm still optimizing.",
          flavorBadge: 'wildcard',
          metricDeltas: { aura: 4, socialFooting: 2, plausibility: 3, larpContinuity: 2, respect: 3 },
          meterDeltas: { impressed: 3, suspicion: 3 },
          characterThinks: "Still optimizing after six weeks. Slightly concerned about the lack of structure but at least he's honest.",
        },
      ],
    },
    {
      turn: 7,
      characterLine:
        "Talking to a user every day is the thing most people skip. — closes laptop — What are you going to do when it doesn't work?",
      options: [
        {
          id: 'hc-t7-a',
          personaTag: 'homeless_cs',
          text: "I'll know it's not working before it stops working. If the 8 actives go to 3 and I can't figure out why from talking to them, I'll cut the product and start the next one. The code is already mine. The failure is just a redirect.",
          flavorBadge: 'prestige',
          metricDeltas: { aura: 15, socialFooting: 6, plausibility: 5, larpContinuity: 5, respect: 9 },
          meterDeltas: { impressed: 15, suspicion: -8 },
          characterThinks: "Leading indicators, conversation-based signals, redirect not failure. He knows how to hold this lightly. I might actually follow him on Twitter.",
        },
        {
          id: 'hc-t7-b',
          personaTag: 'stanford_dropout',
          text: "I have a list of three other problems I want to work on. I'll give this one six months of real effort and if the retention signal isn't there by then, I'll pivot to the next one with everything I learned. The skills compound even if the product doesn't.",
          flavorBadge: 'calculated',
          metricDeltas: { aura: 12, socialFooting: 5, plausibility: 4, larpContinuity: 4, respect: 7 },
          meterDeltas: { impressed: 12, suspicion: -5 },
          characterThinks: "Six-month deadline, three other ideas, skills compound. Clear-eyed and prepared.",
        },
        {
          id: 'hc-t7-c',
          personaTag: 'ai_founder',
          text: "The domain knowledge I'm building is worth it even if this product fails. I'm learning how the data infrastructure market actually works from the inside — that's worth 12 months of my time independent of the outcome.",
          flavorBadge: 'ambitious',
          metricDeltas: { aura: 9, socialFooting: 4, plausibility: 4, larpContinuity: 3, respect: 6 },
          meterDeltas: { impressed: 9, suspicion: -2 },
          characterThinks: "Domain knowledge as the durable output even if the product fails. Correct framing.",
        },
        {
          id: 'hc-t7-d',
          personaTag: 'startup_billionaire',
          text: "Honestly, I don't let myself think about that too much because I find it doesn't serve the work. I'm just focused on making it work.",
          flavorBadge: 'cringe_risk',
          metricDeltas: { aura: -2, socialFooting: -1, plausibility: -1, larpContinuity: -2, respect: -1 },
          meterDeltas: { impressed: -1, suspicion: 8 },
          characterThinks: "He doesn't think about failure because it doesn't 'serve the work.' That's a very fragile thing to build on.",
        },
        {
          id: 'hc-t7-e',
          personaTag: 'crypto_philosopher',
          text: "I think about this a lot actually — there's an interesting question about whether 'it didn't work' is even a well-defined outcome for something at this stage. The failure condition is hard to specify precisely, which makes the decision to stop much harder than it sounds.",
          flavorBadge: 'unhinged',
          metricDeltas: { aura: 3, socialFooting: 1, plausibility: 2, larpContinuity: 1, respect: 2 },
          meterDeltas: { impressed: 2, suspicion: 7 },
          characterThinks: "He philosophized about the definition of failure instead of describing what he would do. I asked what he would do.",
        },
      ],
    },
  ],
}
