import type { ScenarioContent } from '../../features/larpmaxxer/types'

export const scenarioContent: ScenarioContent = {
  scenarioId: 'interview',
  briefDescription:
    'Sandra is VP of Talent at a 600-person fintech company. She has conducted 340 interviews this year. She has a rubric. She is not going to deviate from the rubric. Your job is to seem like a rubric-satisfying human being.',
  openingLine:
    "Thanks for coming in. I'm Sandra — VP of Talent. I want to let you know how this is structured: we'll spend about 50 minutes on behavioral questions, and I'll be taking notes throughout — that's not a signal either way, just process. Let's start with this: Tell me about a time you had to influence someone who had no reason to listen to you.",
  dialogueNodes: [
    {
      turn: 1,
      characterLine:
        "Good. And when you say they eventually came around — what specifically changed their mind? I want to understand the mechanism, not just the outcome.",
      options: [
        {
          id: 'iv-t1-a',
          personaTag: 'consulting_clone',
          text: "What changed it was reframing the conversation from 'you should do this' to 'here's what I'm seeing that you might not be seeing.' I gave her the data she'd need to reach the conclusion herself. She didn't feel persuaded — she felt like she'd figured it out. That was the mechanism.",
          flavorBadge: 'prestige',
          metricDeltas: { aura: 13, socialFooting: 5, plausibility: 5, larpContinuity: 5, respect: 8 },
          meterDeltas: { impressed: 13, suspicion: -5 },
          characterThinks: "He named the psychological mechanism precisely. That's a STAR response that would score well on any rubric.",
        },
        {
          id: 'iv-t1-b',
          personaTag: 'pm_newsletter',
          text: "I found a shared metric she already cared about and mapped my ask onto it. She was optimizing for retention — I showed her that the change I was proposing had a direct retention impact. The ask didn't change, but the framing did.",
          flavorBadge: 'calculated',
          metricDeltas: { aura: 11, socialFooting: 4, plausibility: 4, larpContinuity: 4, respect: 6 },
          meterDeltas: { impressed: 11, suspicion: -3 },
          characterThinks: "Anchor to their metric, then map your ask. Textbook influence and it's correct.",
        },
        {
          id: 'iv-t1-c',
          personaTag: 'startup_billionaire',
          text: "Honestly — I found a small thing I could do that would immediately make her situation easier, did it without being asked, and used the goodwill that created to have a harder conversation later. The relationship preceded the ask.",
          flavorBadge: 'authentic',
          metricDeltas: { aura: 9, socialFooting: 4, plausibility: 4, larpContinuity: 3, respect: 6 },
          meterDeltas: { impressed: 9, suspicion: -2 },
          characterThinks: "Goodwill as a currency. Not the most rigorous framework but it works and he applied it consciously.",
        },
        {
          id: 'iv-t1-d',
          personaTag: 'liberal_arts',
          text: "I think what changed it was creating psychological safety — he needed to be able to say yes without feeling like he'd been outmaneuvered. I was careful to let him take credit for the direction. Most influence is just ego management.",
          flavorBadge: 'wildcard',
          metricDeltas: { aura: 7, socialFooting: 2, plausibility: 3, larpContinuity: 2, respect: 4 },
          meterDeltas: { impressed: 6, suspicion: 3 },
          characterThinks: "'Most influence is just ego management' is either very wise or insufferably cynical. I'm writing it down either way.",
        },
        {
          id: 'iv-t1-e',
          personaTag: 'finance_bro',
          text: "At the end of the day I just laid out the ROI case — showed him the numbers, showed him the downside of not moving, and gave him a deadline for the decision. He responded to financial logic faster than anything else.",
          flavorBadge: 'cringe_risk',
          metricDeltas: { aura: 3, socialFooting: 1, plausibility: 2, larpContinuity: 1, respect: 2 },
          meterDeltas: { impressed: 3, suspicion: 6 },
          characterThinks: "ROI and a deadline. He's treating influence like a closing call. It worked, but the approach is narrow.",
        },
      ],
    },
    {
      turn: 2,
      characterLine:
        "I see. Next question — tell me about a time you failed at something and what you took from it. I want to be explicit: I'm not looking for a weakness reframed as a strength. I want an actual failure.",
      options: [
        {
          id: 'iv-t2-a',
          personaTag: 'consulting_clone',
          text: "I led a process redesign project that I got through to implementation and it flopped — adoption was 20% of what we projected. The failure wasn't the design, it was that I'd solved the problem on paper without building the habit change that would make the solution stick. I'd confused deliverable completion with outcome achievement. I still think about that one.",
          flavorBadge: 'prestige',
          metricDeltas: { aura: 14, socialFooting: 6, plausibility: 5, larpContinuity: 5, respect: 9 },
          meterDeltas: { impressed: 14, suspicion: -7 },
          characterThinks: "That's a real failure with a real lesson and he didn't try to make himself the hero of it. Rubric score: high.",
        },
        {
          id: 'iv-t2-b',
          personaTag: 'startup_billionaire',
          text: "I pushed a product decision that I was right about on the data and wrong about on the timing. We shipped it, it landed badly, and the team had to walk it back six weeks later. I learned that being correct is not the same as being right — context and sequencing matter as much as the call itself.",
          flavorBadge: 'authentic',
          metricDeltas: { aura: 12, socialFooting: 5, plausibility: 4, larpContinuity: 4, respect: 7 },
          meterDeltas: { impressed: 12, suspicion: -5 },
          characterThinks: "'Correct is not the same as right.' That's a genuine insight and the story backs it up.",
        },
        {
          id: 'iv-t2-c',
          personaTag: 'pm_newsletter',
          text: "I underestimated a stakeholder who I'd mentally categorized as low-influence. He wasn't in the formal decision chain but he had informal veto power and he used it to kill a project I'd spent three months building. I now spend a lot more time mapping hidden stakeholders before I start work.",
          flavorBadge: 'calculated',
          metricDeltas: { aura: 10, socialFooting: 4, plausibility: 4, larpContinuity: 3, respect: 6 },
          meterDeltas: { impressed: 10, suspicion: -3 },
          characterThinks: "Missed stakeholder, project killed, systematic change. That's the correct STAR structure for a failure question.",
        },
        {
          id: 'iv-t2-d',
          personaTag: 'student_athlete',
          text: "I took on too much at once and dropped a ball on a client deliverable. The client was unhappy, I had to have a hard conversation with my manager, and we recovered but it cost us. I learned to be more honest about capacity before I commit.",
          flavorBadge: 'glazed',
          metricDeltas: { aura: 4, socialFooting: 2, plausibility: 3, larpContinuity: 2, respect: 3 },
          meterDeltas: { impressed: 4, suspicion: 2 },
          characterThinks: "Overcommitment failure is real but also extremely common. It's the safe answer and I'm noting that.",
        },
        {
          id: 'iv-t2-e',
          personaTag: 'crypto_philosopher',
          text: "I failed at something I don't think I should have been asked to do in the first place — but I'll take ownership of the failure anyway. The project was under-resourced structurally, I didn't escalate that clearly enough, and we underdelivered. I should have named the constraint more loudly.",
          flavorBadge: 'cringe_risk',
          metricDeltas: { aura: -2, socialFooting: -2, plausibility: -1, larpContinuity: -2, respect: -2 },
          meterDeltas: { impressed: -2, suspicion: 10 },
          characterThinks: "He opened with 'I don't think I should have been asked to do this.' In a failure question. I'm marking that.",
        },
      ],
    },
    {
      turn: 3,
      characterLine:
        "That kind of reflection is actually rare. Most people treat this question as a trap. Let's move on — tell me about a time you had to make a high-stakes decision with incomplete information.",
      options: [
        {
          id: 'iv-t3-a',
          personaTag: 'consulting_clone',
          text: "We had a 48-hour window to decide whether to pull a feature ahead of a major release — the data was ambiguous but leaning negative. I made a framework: what's the worst case if I ship and I'm wrong versus the worst case if I pull and I'm wrong? The asymmetry of those two scenarios made the decision clear, even without certainty.",
          flavorBadge: 'prestige',
          metricDeltas: { aura: 14, socialFooting: 6, plausibility: 5, larpContinuity: 5, respect: 8 },
          meterDeltas: { impressed: 14, suspicion: -7 },
          characterThinks: "Decision matrix under time pressure, asymmetric risk framing. This person thinks structurally and they can explain it.",
        },
        {
          id: 'iv-t3-b',
          personaTag: 'startup_billionaire',
          text: "I had to hire someone at a time when I had one good interview, one ambiguous reference, and a deadline. I decided by asking: 'who's the worst version of this person and can I work with them?' The answer was yes. We hired them. They worked out.",
          flavorBadge: 'calculated',
          metricDeltas: { aura: 10, socialFooting: 4, plausibility: 4, larpContinuity: 3, respect: 6 },
          meterDeltas: { impressed: 10, suspicion: -3 },
          characterThinks: "'Who's the worst version of this person and can I work with that?' That's actually a useful heuristic.",
        },
        {
          id: 'iv-t3-c',
          personaTag: 'ai_founder',
          text: "I had to decide whether to build versus buy on a core infrastructure component with a two-day deadline and conflicting technical opinions internally. I set a constraint: I'll decide at 70% confidence, not 95%, because the cost of waiting was higher than the cost of being wrong.",
          flavorBadge: 'ambitious',
          metricDeltas: { aura: 11, socialFooting: 4, plausibility: 4, larpContinuity: 4, respect: 6 },
          meterDeltas: { impressed: 11, suspicion: -4 },
          characterThinks: "70% confidence threshold as an explicit rule. That's a mature decision-making framework.",
        },
        {
          id: 'iv-t3-d',
          personaTag: 'vc_intern',
          text: "I'd argue that all high-stakes decisions are made with incomplete information by definition — so my answer is basically every significant decision I've made. The question is really about your process for structuring uncertainty, which I can talk through.",
          flavorBadge: 'wildcard',
          metricDeltas: { aura: 2, socialFooting: -1, plausibility: -1, larpContinuity: -2, respect: 0 },
          meterDeltas: { impressed: 0, suspicion: 8 },
          characterThinks: "He philosophized instead of answering the question. I have fifteen minutes left in this interview.",
        },
        {
          id: 'iv-t3-e',
          personaTag: 'finance_bro',
          text: "I had to make a go/no-go call on a deal with a Friday deadline and the diligence wasn't complete. I called my most trusted advisor, ran the numbers on the incomplete data, and made the call. You get used to deciding fast when the market doesn't wait.",
          flavorBadge: 'alpha',
          metricDeltas: { aura: 7, socialFooting: 3, plausibility: 3, larpContinuity: 2, respect: 4 },
          meterDeltas: { impressed: 6, suspicion: 2 },
          characterThinks: "Called his advisor, ran the numbers, made the call. Good instincts. Slightly bro-coded delivery.",
        },
      ],
    },
    {
      turn: 4,
      characterLine:
        "Good structural thinking. I want to pivot — tell me about a time you had to give feedback to someone senior to you. What happened and what was the outcome?",
      options: [
        {
          id: 'iv-t4-a',
          personaTag: 'consulting_clone',
          text: "My VP was running a team meeting format that was burning a lot of time without producing decisions. I prepared a one-pager proposing a different structure, framed it as a question rather than a critique — 'would it be useful to have the decision logged before we close?' She adopted it. The key was making it about the outcome she wanted, not about what she was doing wrong.",
          flavorBadge: 'prestige',
          metricDeltas: { aura: 13, socialFooting: 5, plausibility: 5, larpContinuity: 5, respect: 8 },
          meterDeltas: { impressed: 13, suspicion: -6 },
          characterThinks: "Specific behavior, non-threatening framing, outcome focus. That's how you give upward feedback and he clearly knows it.",
        },
        {
          id: 'iv-t4-b',
          personaTag: 'pm_newsletter',
          text: "I told my skip-level that a decision she'd made was going to cause execution problems downstream. I had the specific failure modes documented. She heard it, sat with it for a week, and reversed the decision. I think she needed to feel like the reversal was her idea and I gave her that runway.",
          flavorBadge: 'calculated',
          metricDeltas: { aura: 11, socialFooting: 4, plausibility: 4, larpContinuity: 4, respect: 6 },
          meterDeltas: { impressed: 11, suspicion: -4 },
          characterThinks: "Let the reversal be her idea. He's patient and politically astute.",
        },
        {
          id: 'iv-t4-c',
          personaTag: 'liberal_arts',
          text: "I told my manager directly that the way he was running 1:1s wasn't useful for my development. I asked if we could redesign the format together. He was initially defensive but came around. I think people in senior roles often don't get real feedback and they actually want it.",
          flavorBadge: 'authentic',
          metricDeltas: { aura: 8, socialFooting: 3, plausibility: 3, larpContinuity: 3, respect: 5 },
          meterDeltas: { impressed: 7, suspicion: 2 },
          characterThinks: "Direct feedback to manager about 1:1 format. Bold. It worked. Still slightly alarming for an interview answer.",
        },
        {
          id: 'iv-t4-d',
          personaTag: 'stanford_dropout',
          text: "I told my director that a strategy he was committed to was going to fail for specific structural reasons. He pushed back hard, we disagreed for two months, and then it failed for exactly the reasons I said. We didn't discuss it after.",
          flavorBadge: 'wildcard',
          metricDeltas: { aura: 3, socialFooting: 0, plausibility: 2, larpContinuity: 1, respect: 2 },
          meterDeltas: { impressed: 2, suspicion: 7 },
          characterThinks: "'We didn't discuss it after.' He was right and he apparently wants credit for it. That's a concerning close to a feedback story.",
        },
        {
          id: 'iv-t4-e',
          personaTag: 'crypto_philosopher',
          text: "I gave feedback to a C-suite leader about the company's communication culture — I thought transparency was being systematically suppressed and it was creating alignment problems. She was defensive. I don't think it landed well. I would still do it again.",
          flavorBadge: 'unhinged',
          metricDeltas: { aura: -4, socialFooting: -3, plausibility: -2, larpContinuity: -3, respect: -3 },
          meterDeltas: { impressed: -2, suspicion: 13 },
          characterThinks: "He gave cultural critique feedback to a C-suite executive, it didn't land, and he'd do it again. I'm marking this in multiple categories.",
        },
      ],
    },
    {
      turn: 5,
      characterLine:
        "Next: tell me about a time you had to prioritize ruthlessly when everything felt equally important. How did you make the call?",
      options: [
        {
          id: 'iv-t5-a',
          personaTag: 'pm_newsletter',
          text: "I use a scoring framework when gut feel isn't reliable — impact, reversibility, and time-to-regret. Reversibility is the one people forget. I'll always deprioritize things I can pick up later over things where the window is closing. When everything feels equal, the irreversible things win.",
          flavorBadge: 'prestige',
          metricDeltas: { aura: 14, socialFooting: 5, plausibility: 5, larpContinuity: 5, respect: 8 },
          meterDeltas: { impressed: 13, suspicion: -6 },
          characterThinks: "Reversibility as a prioritization variable. That's a genuinely useful framework and I haven't heard it framed this way before.",
        },
        {
          id: 'iv-t5-b',
          personaTag: 'consulting_clone',
          text: "I asked my manager to make the priority call with full information, rather than making it myself without their input. Prioritization is sometimes a delegation failure — the right move is to surface the conflict, not resolve it alone.",
          flavorBadge: 'calculated',
          metricDeltas: { aura: 10, socialFooting: 4, plausibility: 4, larpContinuity: 3, respect: 6 },
          meterDeltas: { impressed: 10, suspicion: -3 },
          characterThinks: "Escalating a priority conflict as a delegation insight. That's mature. Some interviewers will see that as avoidance — it isn't.",
        },
        {
          id: 'iv-t5-c',
          personaTag: 'startup_billionaire',
          text: "I eliminated two things that felt important but were actually just urgent. Urgency and importance are different and the pressure of 'everything is urgent' is usually a system failure upstream. I traced the urgency source and found a process to fix.",
          flavorBadge: 'ambitious',
          metricDeltas: { aura: 11, socialFooting: 4, plausibility: 4, larpContinuity: 4, respect: 6 },
          meterDeltas: { impressed: 11, suspicion: -4 },
          characterThinks: "Urgency/importance distinction is Covey 101 but he applied it diagnostically rather than as a buzzword. Points for that.",
        },
        {
          id: 'iv-t5-d',
          personaTag: 'student_athlete',
          text: "I made a list, I ranked them by business impact, I did the top three first, and I communicated to stakeholders about what was getting pushed. Transparency about what's not happening is as important as executing on what is.",
          flavorBadge: 'glazed',
          metricDeltas: { aura: 5, socialFooting: 2, plausibility: 3, larpContinuity: 2, respect: 3 },
          meterDeltas: { impressed: 5, suspicion: 1 },
          characterThinks: "Ranking by impact and communicating deprioritizations. Correct and boring. Strong B answer.",
        },
        {
          id: 'iv-t5-e',
          personaTag: 'finance_bro',
          text: "I stack-ranked everything by revenue impact and let the math decide. Anything that wasn't in the top three revenue-weighted outcomes got cut. It wasn't popular but it was defensible.",
          flavorBadge: 'cringe_risk',
          metricDeltas: { aura: 3, socialFooting: 0, plausibility: 2, larpContinuity: 1, respect: 2 },
          meterDeltas: { impressed: 3, suspicion: 5 },
          characterThinks: "Revenue-weighted prioritization is one valid lens and also a signal about what someone optimizes for by default.",
        },
      ],
    },
    {
      turn: 6,
      characterLine:
        "Good. I want to ask a meta question — why do you want this specific role, at this specific stage of your career? I'll be direct: we've had two people in this seat leave inside of 18 months. I want to understand what makes you different.",
      options: [
        {
          id: 'iv-t6-a',
          personaTag: 'consulting_clone',
          text: "The stage is specific to what I'm trying to build. At this size, the decisions I make will still be visible — I won't be a layer below where things actually happen. The risk of the role is also the appeal: the ambiguity is real and I've gotten good at performing in that. The two people who left — I'd want to know why, because if it's structural I need to know that upfront.",
          flavorBadge: 'prestige',
          metricDeltas: { aura: 14, socialFooting: 6, plausibility: 5, larpContinuity: 5, respect: 9 },
          meterDeltas: { impressed: 15, suspicion: -8 },
          characterThinks: "He asked about the turnover directly. That's either bold or self-aware. I think both. I'm going to tell him the truth.",
        },
        {
          id: 'iv-t6-b',
          personaTag: 'startup_billionaire',
          text: "I've done a lot of due diligence on this role and I want to be honest — I'm not coming in with a 10-year plan. I want two to three years of deep impact at a stage I haven't worked at before. But two to three years done right is worth more than a decade of going through motions.",
          flavorBadge: 'authentic',
          metricDeltas: { aura: 10, socialFooting: 4, plausibility: 4, larpContinuity: 3, respect: 6 },
          meterDeltas: { impressed: 9, suspicion: 2 },
          characterThinks: "He's being honest about his timeline. That's either the right answer or a red flag depending on whether the 18-month exits were timeline-driven.",
        },
        {
          id: 'iv-t6-c',
          personaTag: 'pm_newsletter',
          text: "What makes me different is that I've already built the operational muscle this role needs — I'm not coming in to learn on the job, I'm coming in to apply a specific playbook that I've iterated on. The question isn't whether I can do this, it's whether the environment lets me.",
          flavorBadge: 'alpha',
          metricDeltas: { aura: 11, socialFooting: 4, plausibility: 4, larpContinuity: 4, respect: 6 },
          meterDeltas: { impressed: 10, suspicion: -2 },
          characterThinks: "He said 'the question is whether the environment lets me' which is both confident and slightly ominous. I'll probe that.",
        },
        {
          id: 'iv-t6-d',
          personaTag: 'liberal_arts',
          text: "I think the two previous people might have left because the role's success criteria were unclear — I'd want to design those collaboratively in the first 30 days. If I own the definition of success I'm less likely to be surprised by it.",
          flavorBadge: 'calculated',
          metricDeltas: { aura: 8, socialFooting: 3, plausibility: 3, larpContinuity: 3, respect: 5 },
          meterDeltas: { impressed: 8, suspicion: 1 },
          characterThinks: "He hypothesized about why the last people left and proposed a mitigation. I'm 40% annoyed and 60% impressed.",
        },
        {
          id: 'iv-t6-e',
          personaTag: 'vc_intern',
          text: "I'm honestly the most excited about this role of anything I've been in conversation about. The company is at exactly the right inflection point and I think I can add real value quickly. I've done my research and I'm very aligned with the direction.",
          flavorBadge: 'cringe_risk',
          metricDeltas: { aura: -3, socialFooting: -2, plausibility: -2, larpContinuity: -3, respect: -2 },
          meterDeltas: { impressed: -2, suspicion: 10 },
          characterThinks: "'Very aligned with the direction' after I told him two people left inside 18 months. He didn't even acknowledge the signal.",
        },
      ],
    },
    {
      turn: 7,
      characterLine:
        "That's actually a fair question and I'll answer it — one left for a company that offered a VP title, one had a personal situation. Neither was performance-related. We're good on that. Last behavioral: tell me about a time you had to change your mind publicly.",
      options: [
        {
          id: 'iv-t7-a',
          personaTag: 'consulting_clone',
          text: "I advocated in a steering committee for a vendor selection that I'd championed for two months. A week before the final decision, a team member surfaced a pricing issue I'd missed. I walked back my recommendation in the meeting with the full context of what I'd gotten wrong. I've found that changing your mind loudly earns more credibility than getting it right quietly.",
          flavorBadge: 'prestige',
          metricDeltas: { aura: 14, socialFooting: 6, plausibility: 5, larpContinuity: 5, respect: 8 },
          meterDeltas: { impressed: 14, suspicion: -7 },
          characterThinks: "'Changing your mind loudly earns more credibility than getting it right quietly.' That is a real insight and he has the story to back it up.",
        },
        {
          id: 'iv-t7-b',
          personaTag: 'startup_billionaire',
          text: "I wrote a pretty definitive internal memo arguing against a product direction. Six weeks later, data came in that reversed my position. I sent a follow-up memo that started with 'I was wrong about this and here's why' and walked through exactly what I'd missed. It landed better than the original memo.",
          flavorBadge: 'authentic',
          metricDeltas: { aura: 12, socialFooting: 5, plausibility: 4, larpContinuity: 4, respect: 7 },
          meterDeltas: { impressed: 12, suspicion: -5 },
          characterThinks: "Public reversal via written memo. Specific format, specific content, measurable outcome. This is a well-told story.",
        },
        {
          id: 'iv-t7-c',
          personaTag: 'pm_newsletter',
          text: "I had to reverse my position on a pricing strategy in a cross-functional meeting. I reframed it as 'new information requires a new model' — I wasn't wrong before, I had different data before. The room accepted the framing and we moved on quickly.",
          flavorBadge: 'calculated',
          metricDeltas: { aura: 8, socialFooting: 3, plausibility: 3, larpContinuity: 3, respect: 4 },
          meterDeltas: { impressed: 7, suspicion: 3 },
          characterThinks: "'I wasn't wrong, I had different data' — that's a rhetorical hedge on a public reversal story. Slightly suspicious.",
        },
        {
          id: 'iv-t7-d',
          personaTag: 'liberal_arts',
          text: "I'm actually pretty comfortable changing my mind — I don't experience it as a loss of credibility, I experience it as calibration. I've changed positions publicly several times and never found it to be the problem people seem to fear.",
          flavorBadge: 'wildcard',
          metricDeltas: { aura: 4, socialFooting: 1, plausibility: 2, larpContinuity: 1, respect: 2 },
          meterDeltas: { impressed: 3, suspicion: 5 },
          characterThinks: "He answered the meta-question about mind-changing instead of giving me an actual example. That's a STAR violation.",
        },
        {
          id: 'iv-t7-e',
          personaTag: 'homeless_cs',
          text: "I shipped something I'd argued was production-ready and it broke in the first hour. I had to tell the team in real time that I'd misjudged the readiness criteria, walk through what I'd missed, and take ownership of the rollback decision. That was public in the most direct sense.",
          flavorBadge: 'ambitious',
          metricDeltas: { aura: 10, socialFooting: 4, plausibility: 4, larpContinuity: 3, respect: 6 },
          meterDeltas: { impressed: 10, suspicion: -3 },
          characterThinks: "Real-time public reversal in production. High stakes, clear accountability, good ownership. Good answer.",
        },
      ],
    },
    {
      turn: 8,
      characterLine:
        "Good. I have about five minutes left. Do you have questions for me? And I want to say — the one question that tells me more about a candidate than almost anything else is what they ask here.",
      options: [
        {
          id: 'iv-t8-a',
          personaTag: 'consulting_clone',
          text: "Yes — what does success look like at 90 days versus 12 months, and where do those two pictures diverge? I'm asking because the gap between them usually reveals something about how the organization thinks about long-term versus short-term value creation.",
          flavorBadge: 'prestige',
          metricDeltas: { aura: 15, socialFooting: 6, plausibility: 5, larpContinuity: 5, respect: 9 },
          meterDeltas: { impressed: 15, suspicion: -8 },
          characterThinks: "He asked a question that interrogates our incentive structure through a success-definition lens. I have been in talent for 14 years and this is the best closing question I have ever received.",
        },
        {
          id: 'iv-t8-b',
          personaTag: 'pm_newsletter',
          text: "What's the one thing about this role that the job description couldn't capture — the thing that's only visible from inside the company?",
          flavorBadge: 'calculated',
          metricDeltas: { aura: 12, socialFooting: 5, plausibility: 4, larpContinuity: 4, respect: 7 },
          meterDeltas: { impressed: 12, suspicion: -5 },
          characterThinks: "Asking for insider context the JD couldn't convey. Strong question. Shows he knows job descriptions are marketing.",
        },
        {
          id: 'iv-t8-c',
          personaTag: 'startup_billionaire',
          text: "What would you tell someone in this role to stop doing in their first 30 days that seems helpful but actually isn't?",
          flavorBadge: 'ambitious',
          metricDeltas: { aura: 11, socialFooting: 4, plausibility: 4, larpContinuity: 4, respect: 7 },
          meterDeltas: { impressed: 11, suspicion: -4 },
          characterThinks: "Anti-pattern question. Good. Shows he's thinking about failure modes, not just success modes.",
        },
        {
          id: 'iv-t8-d',
          personaTag: 'student_athlete',
          text: "What are the biggest challenges the team is facing right now and how can I have the most immediate impact?",
          flavorBadge: 'glazed',
          metricDeltas: { aura: 3, socialFooting: 2, plausibility: 3, larpContinuity: 2, respect: 2 },
          meterDeltas: { impressed: 3, suspicion: 3 },
          characterThinks: "That is the most common closing question in the history of job interviews. I have heard it 300 times this year.",
        },
        {
          id: 'iv-t8-e',
          personaTag: 'crypto_philosopher',
          text: "I'm curious — when you're evaluating candidates, what's the thing that your rubric systematically fails to capture? What are you losing by having a rubric at all?",
          flavorBadge: 'unhinged',
          metricDeltas: { aura: -5, socialFooting: -4, plausibility: -3, larpContinuity: -4, respect: -3 },
          meterDeltas: { impressed: -2, suspicion: 15 },
          characterThinks: "He asked me to justify my rubric in a behavioral interview. He is critiquing my methodology while I am evaluating him with that methodology. This is a no.",
        },
      ],
    },
  ],
}
